/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.healthCare;

import business.Enterprise.Enterprise;
import business.UserAccount.UserAccount;
import business.patient.Patient;
import business.person.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ilanigam17
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    private Person person;
    private Patient patient;
    private JPanel userProcessContainer;
    private UserAccount account;
    private Enterprise enterprise;

    /**
     * Creates new form CreatePatientJPanel
     */
    public CreatePatientJPanel(UserAccount account, Enterprise enterprise, Person person, JPanel userProcessContainer) {
        initComponents();
        this.account = account;
        this.person = person;
        this.patient = person.getPatient();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        nameJTextField.setText(person.getName());
        idJTextField.setText(String.valueOf(person.getId()));
        ageJTextField.setText(String.valueOf(person.getAge()));
        populateBoodgrpCombo();
    }

    public void populateBoodgrpCombo() {
        bloodgrpCombo1.addItem("AB");
        bloodgrpCombo1.addItem("+A");
        bloodgrpCombo1.addItem("-A");
        bloodgrpCombo1.addItem("-AB");
        bloodgrpCombo1.addItem("+A");
        bloodgrpCombo1.addItem("-A");
        bloodgrpCombo1.addItem("-O");
        bloodgrpCombo1.addItem("+O");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ageJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        createPatientJButton = new javax.swing.JButton();
        nameJTextField = new javax.swing.JTextField();
        idJTextField = new javax.swing.JTextField();
        addVitalJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bloodgrpCombo1 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Patient Record");

        jLabel6.setText("Name");

        jLabel7.setText("ID");

        jLabel8.setText("Age");

        createPatientJButton.setText("Create");
        createPatientJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPatientJButtonActionPerformed(evt);
            }
        });

        nameJTextField.setEditable(false);
        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });

        idJTextField.setEditable(false);
        idJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idJTextFieldActionPerformed(evt);
            }
        });

        addVitalJButton.setText("Add VitalInfo");
        addVitalJButton.setEnabled(false);
        addVitalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVitalJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Blood Group");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(142, 142, 142)
                                    .addComponent(createPatientJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addVitalJButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bloodgrpCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel5)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addVitalJButton)
                            .addComponent(createPatientJButton)))
                    .addComponent(bloodgrpCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createPatientJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPatientJButtonActionPerformed
        // TODO add your handling code here:
        String errMsg = validateFields();
        if (errMsg.toString().isEmpty()) {
            createPatientRec();
            JOptionPane.showMessageDialog(null, "Patient record has been created successfully!", "Congralutions!", JOptionPane.INFORMATION_MESSAGE);
            //resetCreatePatient();
            addVitalJButton.setEnabled(true);
            ageJTextField.setEditable(false);
//            docNameJTextField.setEditable(false);
//            phNameJTextField.setEditable(false);
        } else {
            JOptionPane.showMessageDialog(null, errMsg.toString(), "Abort!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createPatientJButtonActionPerformed

    private void idJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idJTextFieldActionPerformed

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void addVitalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVitalJButtonActionPerformed
        // TODO add your handling code here:
        ManagePatientVitalInfoJPanel addVitalInfoJPanel = new ManagePatientVitalInfoJPanel(account, enterprise, patient, userProcessContainer);
        userProcessContainer.add("ManagePatientVitalInfoJPanel", addVitalInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addVitalJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    public void resetCreatePatient() {
        ageJTextField.setText("");
        // docNameJTextField.setText("");
        // phNameJTextField.setText("");
    }

    public String validateFields() {
        String errMsg = "";

        if (ageJTextField.getText().isEmpty()) {
            errMsg = errMsg + "Patient age is manadatory\n";
        } else if (!(ageJTextField.getText().trim()).matches("[0-9]*")) {
            errMsg = errMsg + "Patient age is not a valid input\n";
        }

//        if(docNameJTextField.getText().isEmpty()){
//           errMsg=errMsg+"Document name is manadatory\n"; 
//        }else if((docNameJTextField.getText().trim()).isEmpty()){
//           errMsg=errMsg+"Document name is not a valid input\n"; 
//        }
//        
//        if(phNameJTextField.getText().isEmpty()){
//           errMsg=errMsg+"Pharmacy name is manadatory\n"; 
//        }else if((phNameJTextField.getText().trim()).isEmpty()){
//           errMsg=errMsg+"Pharmacy name is not a valid input\n"; 
//        }
        return errMsg;
    }

    public void createPatientRec() {
        patient = new Patient();
        patient.setName(person.getName());
        patient.setId(String.valueOf(person.getId()));
        patient.setAge(Integer.parseInt(ageJTextField.getText().trim()));
        patient.setBloodGrp(String.valueOf(bloodgrpCombo1.getSelectedItem()));
//            patient.setDocName(docNameJTextField.getText().trim());
//            patient.setPharmacyName(phNameJTextField.getText().trim());
        this.person.setPatient(patient);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVitalJButton;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox bloodgrpCombo1;
    private javax.swing.JButton createPatientJButton;
    private javax.swing.JTextField idJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameJTextField;
    // End of variables declaration//GEN-END:variables
}
