/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.healthCare;

import userInterface.doctor.*;
import business.UserAccount.UserAccount;
import business.WorkQueue.PersonalHealthIssueWorkRequest;
import business.patient.VitalSignInfo;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ViewHealthReqResultJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    PersonalHealthIssueWorkRequest request;
    private static int count = 1;
    private UserAccount acc;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ViewHealthReqResultJPanel(JPanel userProcessContainer, PersonalHealthIssueWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.acc = request.getSender();
        populateBoodgrpCombo();
        String patientName = ((PersonalHealthIssueWorkRequest) request).getSender().getUsername().toString()+"_"+((PersonalHealthIssueWorkRequest) request).getId();
        qrCodelabel.setIcon(new ImageIcon(patientName + ".jpg"));
        populatePatientInfo();

        request.setCheckedNotification(false);
        populateIssueSummary();
        populateFileTable();
        bloodgrpCombo1.setEnabled(false);
    }

    public void populateBoodgrpCombo() {
        bloodgrpCombo1.addItem("AB");
        bloodgrpCombo1.addItem("+A");
        bloodgrpCombo1.addItem("-A");
        bloodgrpCombo1.addItem("-AB");
        bloodgrpCombo1.addItem("+A");
        bloodgrpCombo1.addItem("-A");
        bloodgrpCombo1.addItem("-O");
        bloodgrpCombo1.addItem("+O");
    }

    public void populatePatientInfo() {
        nameJTextField1.setText(acc.getPerson().getName());
        // idJTextField1.setText(request.getId());
        ageJTextField1.setText(String.valueOf(acc.getPerson().getPatient().getAge()));
        bloodgrpCombo1.setSelectedItem(acc.getPerson().getPatient().getBloodGrp());
        phNumJLbl.setText(String.valueOf(acc.getPerson().getPhoneNum()));
        emailInfoJLbl.setText(acc.getPerson().getEmailId());
        populateVitalInfo();

    }

    public void populateIssueSummary() {
        issueDetailsJtxt.setText(request.getIssueDetails());
        // JScrollPane scroll= new JScrollPane(issueDetailsJtxt,JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        messageJLbl.setText(request.getMessage());
        resultJtxtArea.setText(request.getTestResult());
    }

    public void populateVitalInfo() {
        VitalSignInfo vitalSign = request.getLatestVital();
        respRateJTextField.setText(String.valueOf(vitalSign.getRespRate()));
        heartRateJTextField.setText(String.valueOf(vitalSign.getHeartRate()));
        dateOfTakenJTxt.setText(String.valueOf(vitalSign.getCurrentTime()));
        sysBPJTextField.setText(String.valueOf(vitalSign.getSystolicBP()));
        weightJTextField.setText(String.valueOf(vitalSign.getWeight()));
        hivStatusJTxt.setText(String.valueOf(vitalSign.getHivStatus()));

    }

    public void populateFileTable() {
      //  System.err.println("inside populateFileTable");
        DefaultTableModel dtm = (DefaultTableModel) fileJtable.getModel();
        dtm.setRowCount(0);

        int fileCount = 1;
        for (File file : request.getUploadList()) {
            Object row[] = new Object[2];
       //     System.err.println("inside populateFileTable" + file.getAbsolutePath() + " ::" + file);
            // row[0]="file"+fileCount++;
            row[0] = file.getAbsolutePath();
            row[1] = file;
            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        qrCodelabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nameJTextField1 = new javax.swing.JTextField();
        bloodgrpCombo1 = new javax.swing.JComboBox();
        ageJTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        emailInfoJLbl = new javax.swing.JLabel();
        phNumJLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issueDetailsJtxt = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        messageJLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultJtxtArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        fileJtable = new javax.swing.JTable();
        vitalInfoJPanel = new javax.swing.JPanel();
        heartRateJTextField = new javax.swing.JTextField();
        sysBPJTextField = new javax.swing.JTextField();
        weightJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        respRateJTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dateOfTakenJTxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        hivStatusJText = new javax.swing.JLabel();
        hivStatusJTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2500, 32767));
        setPreferredSize(new java.awt.Dimension(2500, 830));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Result");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("View Request detail ");

        qrCodelabel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel10.setText("Age");

        nameJTextField1.setEditable(false);
        nameJTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextField1ActionPerformed(evt);
            }
        });

        bloodgrpCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodgrpCombo1ActionPerformed(evt);
            }
        });

        ageJTextField1.setEditable(false);

        jLabel11.setText("Blood Group");

        jLabel12.setText("Name");

        emailInfoJLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailInfoJLbl.setForeground(new java.awt.Color(51, 51, 255));
        emailInfoJLbl.setText("No Email Address Available");

        phNumJLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phNumJLbl.setForeground(new java.awt.Color(0, 0, 255));
        phNumJLbl.setText("No Phone Number Available");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(nameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(emailInfoJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phNumJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ageJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bloodgrpCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodgrpCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(39, 39, 39)
                .addComponent(emailInfoJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phNumJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        issueDetailsJtxt.setEditable(false);
        issueDetailsJtxt.setColumns(20);
        issueDetailsJtxt.setRows(5);
        jScrollPane1.setViewportView(issueDetailsJtxt);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Issue details:");

        messageJLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        messageJLbl.setForeground(new java.awt.Color(0, 102, 102));
        messageJLbl.setText("123");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Issue Summary:");

        resultJtxtArea.setColumns(20);
        resultJtxtArea.setRows(5);
        jScrollPane2.setViewportView(resultJtxtArea);

        fileJtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "File Name", "Uploads"
            }
        ));
        fileJtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileJtableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(fileJtable);
        if (fileJtable.getColumnModel().getColumnCount() > 0) {
            fileJtable.getColumnModel().getColumn(1).setHeaderValue("Uploads");
        }

        vitalInfoJPanel.setBackground(new java.awt.Color(239, 239, 239));
        vitalInfoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Vital Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        heartRateJTextField.setEnabled(false);

        sysBPJTextField.setEnabled(false);

        weightJTextField.setEnabled(false);
        weightJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightJTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Respiratory Rate");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Heart Rate");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Systolic Blood Pressure");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Weight(In pounds)");

        respRateJTextField.setEnabled(false);
        respRateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respRateJTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Date of taken");

        dateOfTakenJTxt.setEditable(false);

        jButton3.setText("History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        hivStatusJText.setText("HIV Status");

        hivStatusJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hivStatusJTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vitalInfoJPanelLayout = new javax.swing.GroupLayout(vitalInfoJPanel);
        vitalInfoJPanel.setLayout(vitalInfoJPanelLayout);
        vitalInfoJPanelLayout.setHorizontalGroup(
            vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vitalInfoJPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vitalInfoJPanelLayout.createSequentialGroup()
                        .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13))
                        .addGap(41, 49, Short.MAX_VALUE))
                    .addGroup(vitalInfoJPanelLayout.createSequentialGroup()
                        .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(vitalInfoJPanelLayout.createSequentialGroup()
                                .addGap(0, 80, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(vitalInfoJPanelLayout.createSequentialGroup()
                                .addComponent(hivStatusJText)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(respRateJTextField)
                    .addComponent(heartRateJTextField)
                    .addComponent(sysBPJTextField)
                    .addComponent(weightJTextField)
                    .addComponent(hivStatusJTxt)
                    .addComponent(dateOfTakenJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        vitalInfoJPanelLayout.setVerticalGroup(
            vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vitalInfoJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(dateOfTakenJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(respRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(heartRateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sysBPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(weightJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vitalInfoJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vitalInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hivStatusJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hivStatusJText)))
                    .addGroup(vitalInfoJPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton3)))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(backJButton))
                                        .addGap(49, 49, 49))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(messageJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(qrCodelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vitalInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vitalInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qrCodelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void nameJTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextField1ActionPerformed

    private void bloodgrpCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodgrpCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodgrpCombo1ActionPerformed

    private void weightJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightJTextFieldActionPerformed

    private void respRateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respRateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_respRateJTextFieldActionPerformed

    private void hivStatusJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hivStatusJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hivStatusJTxtActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ReportingPatientVitalHistJPanel reportingPatientVitalHistJPanel = new ReportingPatientVitalHistJPanel(acc.getPerson().getPatient(), userProcessContainer);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("reportingPatientVitalHistJPanel", reportingPatientVitalHistJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fileJtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileJtableMouseClicked
        // TODO add your handling code here:
        int row = fileJtable.getSelectedRow();
        String currentLine;
        String value = (String) (fileJtable.getModel().getValueAt(row, 0));
        try {
            for (File file : request.getUploadList()) {
                if (fileJtable.getModel().getValueAt(row, 0).equals(file.getAbsolutePath())) {
                    BufferedReader br = new BufferedReader(new FileReader((File) fileJtable.getModel().getValueAt(row, 1)));
                    //System.err.println("ila.."+request.getSender().getPerson().getId()+"_"+file.getAbsolutePath().substring((file.getAbsolutePath().lastIndexOf("\'")),(file.getAbsolutePath().length()-1)));
                    FileWriter writer = new FileWriter("parent\\" + request.getSender().getPerson().getId() + "_Myfile.txt");
                    BufferedWriter bufferedWriter = new BufferedWriter(writer);
                    //writer = Files.newBufferedWriter(writer, StandardCharsets.UTF_8);
                    while ((currentLine = br.readLine()) != null) {
                        bufferedWriter.write(currentLine);
                        // must do this: .readLine() will have stripped line endings
                        bufferedWriter.newLine();

                    }
                    bufferedWriter.close();
                    JOptionPane.showMessageDialog(null, "File Saved at location: " + "\\parent\\" + request.getSender().getPerson().getId() + "_Myfile.txt");
                    // readFile(request.getSender().getPerson().getId()+"_Myfile.txt");

                    break;
                }
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_fileJtableMouseClicked

    /**
     * Open and read a file, and return the lines in the file as a list of
     * Strings. (Demonstrates Java FileReader, BufferedReader, and Java5.)
     */
    private void readFile(String filename) {
        List<String> records = new ArrayList<String>();
        try {
            BufferedReader reader = new BufferedReader(new FileReader(filename));
            String line;
            while ((line = reader.readLine()) != null) {
                records.add(line);
            }

            reader.close();

        } catch (Exception e) {
        ///    System.err.format("Exception occurred trying to read '%s'.", filename);
         //   e.printStackTrace();

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageJTextField1;
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox bloodgrpCombo1;
    private javax.swing.JTextField dateOfTakenJTxt;
    private javax.swing.JLabel emailInfoJLbl;
    private javax.swing.JTable fileJtable;
    private javax.swing.JTextField heartRateJTextField;
    private javax.swing.JLabel hivStatusJText;
    private javax.swing.JTextField hivStatusJTxt;
    private javax.swing.JTextArea issueDetailsJtxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel messageJLbl;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JLabel phNumJLbl;
    private javax.swing.JLabel qrCodelabel;
    private javax.swing.JTextField respRateJTextField;
    private javax.swing.JTextArea resultJtxtArea;
    private javax.swing.JTextField sysBPJTextField;
    private javax.swing.JPanel vitalInfoJPanel;
    private javax.swing.JTextField weightJTextField;
    // End of variables declaration//GEN-END:variables
}
