/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.badMoodDay;

import java.awt.CardLayout;
import java.io.IOException;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ilanigam17
 */
public class BookSuggestionJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    /**
     * Creates new form BookSuggestionJPanel
     */
    public BookSuggestionJPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        DefaultTableModel dtm = (DefaultTableModel) listURLtable.getModel();
        dtm.setRowCount(0);
        Object row[] = new Object[2];

        row[1] = "http://www.whatshouldireadnext.com/index.php?q=";
        row[0] = "What Should I read next";
        dtm.addRow(row);
        row[1] = String.valueOf("http://bookboon.com/en/search?q=");
        row[0] = "Book boon";
        dtm.addRow(row);
        row[1] = String.valueOf("https://www.google.com/#q=");
        row[0] = "Google";
        dtm.addRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        courseNameJTxt = new javax.swing.JTextField();
        keywordJTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        searchWebJBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listURLtable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Course Name:");

        keywordJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keywordJTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Keyword:");

        searchWebJBtn.setText("Search Web");
        searchWebJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchWebJBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Book Suggestions");

        listURLtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Web links"
            }
        ));
        jScrollPane1.setViewportView(listURLtable);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Select any of the below links, then click 'Search Web' :");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(keywordJTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(courseNameJTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(searchWebJBtn))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel3)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(courseNameJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(keywordJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(searchWebJBtn)
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void keywordJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keywordJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keywordJTxtActionPerformed

    private void searchWebJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchWebJBtnActionPerformed

        if (listURLtable.getSelectedRow() > -1) {
            try {

                DefaultTableModel dtm = (DefaultTableModel) listURLtable.getModel();
                String URL = (String) dtm.getValueAt(listURLtable.getSelectedRow(), 1);

                if (listURLtable.getSelectedRow() == 0) {
                    URL = URL + courseNameJTxt.getText().replace(" ", "+") + "+" + keywordJTxt.getText().replace(" ", "+");
                } else {
                    URL = URL + courseNameJTxt.getText().replace(" ", "+") + "+books" + keywordJTxt.getText().replace(" ", "+");
                }

                java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
            } catch (Exception e) {
                String URL = "https://www.google.com/";
                try {
                    java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
                } catch (IOException ex) {
                  //  System.err.println("BookSuggestion........" + ex);
                }//catch IO
            }//catch exception

        }//end if

    }//GEN-LAST:event_searchWebJBtnActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField courseNameJTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keywordJTxt;
    private javax.swing.JTable listURLtable;
    private javax.swing.JButton searchWebJBtn;
    // End of variables declaration//GEN-END:variables
}
