/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.badMoodDay;

import business.Enterprise.Enterprise;
import business.UserAccount.UserAccount;
import business.WorkQueue.FinancialWorkRequest;
import business.WorkQueue.WorkRequest;
import business.ecosystem.Ecosystem;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.appointments.AppointmentSchdTeacherResJFrame;

/**
 *
 * @author ilanigam17
 */
public class StudentSanctionFinanceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount userAccount;

    private Enterprise enterprise;
    private Ecosystem ecosystem;
    private WorkRequest workReq;

    /**
     * Creates new form SanctionManagerFinanceJPanel1
     */
    public StudentSanctionFinanceJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;

        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        // populateNotification();  
        populateSanctionOrgReqTable();
//        approveJBtn.setVisible(false);
//        denyJBtn.setVisible(false);
    }

    public void populateSanctionOrgReqTable() {
        DefaultTableModel dtm = (DefaultTableModel) sanctionOrgReqJTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            if (request instanceof FinancialWorkRequest) {
                Object row[] = new Object[7];
                row[0] = request;
                row[1] = userAccount;
                row[2] = ((FinancialWorkRequest) request).getAppointmentReq().getDateOfAppointment();
                row[3] = ((FinancialWorkRequest) request).getApprovedAmt();
                row[4] = ((FinancialWorkRequest) request).getApprovalStatus();
                row[5] = ((FinancialWorkRequest) request).getAppointmentReq().getDateOfAppointment();
                row[6] = ((FinancialWorkRequest) request).getApprovedDate();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        sanctionOrgReqJTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        fundingJPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        caseFundsDescJTxt = new javax.swing.JTextArea();
        caseFamilyIncomeJTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        caseFamilyExpJTxt = new javax.swing.JTextField();
        caseFundReqJTxt = new javax.swing.JTextField();
        caseAmtNeedJTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        caseDescJtxt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 255, 255));

        sanctionOrgReqJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Case ID", "SenderId", "Event date", "Amt Sanctioned", "Status", "Approver", "Approved date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sanctionOrgReqJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sanctionOrgReqJTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(sanctionOrgReqJTable);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Sanctioned Finance Portal");

        fundingJPanel.setBackground(new java.awt.Color(255, 255, 255));
        fundingJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Case details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        caseFundsDescJTxt.setEditable(false);
        caseFundsDescJTxt.setColumns(20);
        caseFundsDescJTxt.setRows(5);
        jScrollPane3.setViewportView(caseFundsDescJTxt);

        caseFamilyIncomeJTxt.setEditable(false);
        caseFamilyIncomeJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseFamilyIncomeJTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Total Family funds per month:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Case Study for funds:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Funds required:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Family Expenses per month:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Amount approved:");

        caseFamilyExpJTxt.setEditable(false);

        caseFundReqJTxt.setEditable(false);
        caseFundReqJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseFundReqJTxtActionPerformed(evt);
            }
        });

        caseAmtNeedJTxt.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Description:");

        caseDescJtxt.setEditable(false);
        caseDescJtxt.setColumns(20);
        caseDescJtxt.setRows(5);
        jScrollPane4.setViewportView(caseDescJtxt);

        jButton1.setText("View Appointment details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fundingJPanelLayout = new javax.swing.GroupLayout(fundingJPanel);
        fundingJPanel.setLayout(fundingJPanelLayout);
        fundingJPanelLayout.setHorizontalGroup(
            fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundingJPanelLayout.createSequentialGroup()
                .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundingJPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(backJButton))
                    .addGroup(fundingJPanelLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, fundingJPanelLayout.createSequentialGroup()
                                .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(30, 30, 30)
                                .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(caseFamilyIncomeJTxt)))
                            .addGroup(fundingJPanelLayout.createSequentialGroup()
                                .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGap(36, 36, 36)
                                .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(caseFundReqJTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caseFamilyExpJTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(caseAmtNeedJTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jButton1))))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        fundingJPanelLayout.setVerticalGroup(
            fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundingJPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(fundingJPanelLayout.createSequentialGroup()
                        .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caseFamilyIncomeJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(caseFamilyExpJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(caseFundReqJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5))
                    .addComponent(caseAmtNeedJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(fundingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundingJPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2))
                    .addGroup(fundingJPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(backJButton)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel7)
                        .addGap(0, 567, Short.MAX_VALUE))
                    .addComponent(fundingJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fundingJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void caseFamilyIncomeJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseFamilyIncomeJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseFamilyIncomeJTxtActionPerformed

    private void sanctionOrgReqJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sanctionOrgReqJTableMouseClicked
        // TODO add your handling code here:

        if (sanctionOrgReqJTable.getSelectedRow() > -1) {
            //approveJBtn.setVisible(true);
            // denyJBtn.setVisible(true);
            DefaultTableModel dtm = (DefaultTableModel) sanctionOrgReqJTable.getModel();
            FinancialWorkRequest finWorkReq = (FinancialWorkRequest) dtm.getValueAt(sanctionOrgReqJTable.getSelectedRow(), 0);
            this.workReq = finWorkReq;
            caseDescJtxt.setText(finWorkReq.getAppointmentReq().getReasonOfAppointment());
            caseFamilyIncomeJTxt.setText(String.valueOf(finWorkReq.getSender().getPerson().getFundsAvail().getFamilyMonIncome()));
            caseFamilyExpJTxt.setText(String.valueOf(finWorkReq.getSender().getPerson().getFundsAvail().getFamilyMonExpense()));
            caseFundReqJTxt.setText(String.valueOf(finWorkReq.getAppointmentReq().getTotalFeeOfAppointment()));
            caseAmtNeedJTxt.setText(String.valueOf(finWorkReq.getApprovedAmt()));
            caseFundsDescJTxt.setText(finWorkReq.getCaseStudyDetails());

        }
    }//GEN-LAST:event_sanctionOrgReqJTableMouseClicked
    public void changeColor(String caseStrength) {
        if ((!caseStrength.isEmpty()) && caseStrength.equalsIgnoreCase("Strong")) {
            fundingJPanel.setBackground(Color.green);
        }
        if ((!caseStrength.isEmpty()) && caseStrength.equalsIgnoreCase("Managable")) {
            fundingJPanel.setBackground(Color.blue);
        }
        if ((!caseStrength.isEmpty()) && caseStrength.equalsIgnoreCase("weak")) {
            fundingJPanel.setBackground(Color.red);
        }

    }
    private void caseFundReqJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseFundReqJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseFundReqJTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        //tabbedPane.setVisible(false);
        AppointmentSchdTeacherResJFrame appointmentSchdTeacherResJFrame = new AppointmentSchdTeacherResJFrame(((FinancialWorkRequest) this.workReq), this.workReq.getSender(), this.workReq.getReceiver(), enterprise, ecosystem, this);
        appointmentSchdTeacherResJFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField caseAmtNeedJTxt;
    private javax.swing.JTextArea caseDescJtxt;
    private javax.swing.JTextField caseFamilyExpJTxt;
    private javax.swing.JTextField caseFamilyIncomeJTxt;
    private javax.swing.JTextField caseFundReqJTxt;
    private javax.swing.JTextArea caseFundsDescJTxt;
    private javax.swing.JPanel fundingJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable sanctionOrgReqJTable;
    // End of variables declaration//GEN-END:variables
}
