/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.badMoodDay;

import business.Enterprise.Enterprise;
import business.Organization.Organization;
import business.Organization.Community.StudentOrganization;
import business.UserAccount.UserAccount;
import business.person.ChatConversation;
import business.WorkQueue.StudentPortalWorkRequest;
import business.WorkQueue.WorkRequest;
import business.ecosystem.Ecosystem;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ilanigam17
 */
public class StudentPortalJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount acc;
    private Enterprise enterprise;
    private Ecosystem ecosystem;
    private WorkRequest request;
    private ChatConversation selConversation;

    /**
     * Creates new form NewJPanel
     */
    public StudentPortalJPanel(JPanel userProcessContainer, UserAccount acc, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.acc = acc;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        populatePortalTable();
        populateStatusCombo();
        postQueryJPanel.setVisible(true);
        postSolPanel.setVisible(false);
        viewProposedSolPanel.setVisible(false);
        this.request = null;
        this.selConversation = null;
        jLabel2.setText(acc.getUsername());
        //viewSolScrollPane.setVisible(false);
        // postQueryScrollPane.setVisible(false);
        // postSolScrollPane.setVisible(false);
    }

    public void populateStatusCombo() {
        DefaultComboBoxModel dcm = (DefaultComboBoxModel) inputStatusJCombo.getModel();
        inputStatusJCombo.addItem("Need Help!");
        inputStatusJCombo.addItem("Closed!");
        inputStatusJCombo.setSelectedItem(0);
    }

    public void populatePortalTable() {
        DefaultTableModel dtm = (DefaultTableModel) studentPortalJTable.getModel();
        dtm.setRowCount(0);

        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof StudentOrganization) {
                for (WorkRequest request : org.getWorkQueue().getWorkRequestList()) {
                    if (request instanceof StudentPortalWorkRequest) {
                        Object row[] = new Object[8];
                        row[0] = request;
                        row[1] = ((StudentPortalWorkRequest) request).getSender().getUsername();
                        row[2] = ((StudentPortalWorkRequest) request).getRequestDate();
                        row[3] = request.getMessage();
                        row[4] = ((StudentPortalWorkRequest) request).getQuery();
                        row[5] = (((StudentPortalWorkRequest) request).getSolDiscussionList().size() > 0) ? ("True: #Solution= " + ((StudentPortalWorkRequest) request).getSolDiscussionList().size()) : "False";
                        row[6] = request.getStatus();
                        row[7] = request.getReceiver();
                        dtm.addRow(row);
                    }
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentPortalJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        dspPostQueryPanelJBtn = new javax.swing.JButton();
        dspSolPanelJBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bottomlayeredPane = new javax.swing.JLayeredPane();
        viewProposedSolPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        proposedSolJList = new javax.swing.JList();
        jScrollPane9 = new javax.swing.JScrollPane();
        evalPropSolJTxtArea = new javax.swing.JTextArea();
        evalSubjectJText = new javax.swing.JTextField();
        datePostJLbl = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        evalReplyJTxt = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        evalReplyJButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        postQueryJPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        inputQueryJTxt = new javax.swing.JTextArea();
        postQueryJBtn = new javax.swing.JButton();
        inputSubjectJtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputStatusJCombo = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        backJButton1 = new javax.swing.JButton();
        postSolPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        QueryJTxtArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        solutionJTxtArea = new javax.swing.JTextArea();
        postJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        subjectSolPaneLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        senderIdJLbl = new javax.swing.JLabel();
        dateOfPostJLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        todayDateJLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        statusJlabel = new javax.swing.JLabel();
        backJButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        studentPortalJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Sender Id", "Date Posted", "Subject", "Query", "Solution Available", "Status"
            }
        ));
        jScrollPane1.setViewportView(studentPortalJTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Student Portal");

        dspPostQueryPanelJBtn.setText("Post Query");
        dspPostQueryPanelJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dspPostQueryPanelJBtnActionPerformed(evt);
            }
        });

        dspSolPanelJBtn.setText("Post Solution");
        dspSolPanelJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dspSolPanelJBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Solutions");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        proposedSolJList.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        proposedSolJList.setForeground(new java.awt.Color(0, 102, 102));
        proposedSolJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proposedSolJListMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(proposedSolJList);

        evalPropSolJTxtArea.setEditable(false);
        evalPropSolJTxtArea.setColumns(20);
        evalPropSolJTxtArea.setRows(5);
        jScrollPane9.setViewportView(evalPropSolJTxtArea);

        evalSubjectJText.setEditable(false);

        evalReplyJTxt.setColumns(20);
        evalReplyJTxt.setRows(5);
        jScrollPane10.setViewportView(evalReplyJTxt);

        jLabel12.setText("Subject");

        jLabel13.setText("Proposed Sol");

        jLabel14.setText("Reply");

        evalReplyJButton.setText("Reply");
        evalReplyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evalReplyJButtonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel15.setText("Select whose reply you wanna see:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Evaluate Reponse");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewProposedSolPanelLayout = new javax.swing.GroupLayout(viewProposedSolPanel);
        viewProposedSolPanel.setLayout(viewProposedSolPanelLayout);
        viewProposedSolPanelLayout.setHorizontalGroup(
            viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProposedSolPanelLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(viewProposedSolPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addGroup(viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewProposedSolPanelLayout.createSequentialGroup()
                                .addGroup(viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                                        .addComponent(datePostJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(evalSubjectJText))
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(evalReplyJButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel16)))
                    .addComponent(backJButton))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        viewProposedSolPanelLayout.setVerticalGroup(
            viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewProposedSolPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewProposedSolPanelLayout.createSequentialGroup()
                        .addComponent(datePostJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(evalSubjectJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGroup(viewProposedSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(viewProposedSolPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewProposedSolPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(evalReplyJButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(viewProposedSolPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(backJButton)
                        .addContainerGap(64, Short.MAX_VALUE))))
        );

        inputQueryJTxt.setColumns(20);
        inputQueryJTxt.setRows(5);
        jScrollPane6.setViewportView(inputQueryJTxt);

        postQueryJBtn.setText("Post Query");
        postQueryJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postQueryJBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Subject:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Add a query");

        inputStatusJCombo.setEnabled(false);

        jLabel17.setText("Status:");

        jLabel18.setText("Describe your query:");

        backJButton1.setText("Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout postQueryJPanelLayout = new javax.swing.GroupLayout(postQueryJPanel);
        postQueryJPanel.setLayout(postQueryJPanelLayout);
        postQueryJPanelLayout.setHorizontalGroup(
            postQueryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postQueryJPanelLayout.createSequentialGroup()
                .addGroup(postQueryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(postQueryJPanelLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputStatusJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(postQueryJPanelLayout.createSequentialGroup()
                        .addContainerGap(94, Short.MAX_VALUE)
                        .addGroup(postQueryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backJButton1)
                            .addGroup(postQueryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(postQueryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputSubjectJtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(postQueryJBtn))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        postQueryJPanelLayout.setVerticalGroup(
            postQueryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postQueryJPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(postQueryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(inputStatusJCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(61, 61, 61)
                .addGroup(postQueryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSubjectJtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(postQueryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(postQueryJBtn)
                .addGap(45, 45, 45)
                .addComponent(backJButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        QueryJTxtArea.setColumns(20);
        QueryJTxtArea.setRows(5);
        jScrollPane3.setViewportView(QueryJTxtArea);

        solutionJTxtArea.setColumns(20);
        solutionJTxtArea.setRows(5);
        jScrollPane4.setViewportView(solutionJTxtArea);

        postJBtn.setText("Post!");
        postJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postJBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Your Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Post a Solution");

        subjectSolPaneLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subjectSolPaneLabel.setText("Subject");

        jLabel5.setText("Sender ID:");

        jLabel6.setText("Date posted:");

        jLabel10.setText("Today date:");

        jLabel7.setText("Status:");

        jLabel19.setText("Propose Solution:");

        jLabel20.setText("Query description:");

        backJButton2.setText("Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout postSolPanelLayout = new javax.swing.GroupLayout(postSolPanel);
        postSolPanel.setLayout(postSolPanelLayout);
        postSolPanelLayout.setHorizontalGroup(
            postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postSolPanelLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton2)
                    .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, postSolPanelLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(263, 263, 263))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, postSolPanelLayout.createSequentialGroup()
                            .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(postJBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(postSolPanelLayout.createSequentialGroup()
                            .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(postSolPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(senderIdJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(postSolPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dateOfPostJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, postSolPanelLayout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(statusJlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(todayDateJLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(0, 25, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, postSolPanelLayout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(subjectSolPaneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        postSolPanelLayout.setVerticalGroup(
            postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(postSolPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addComponent(subjectSolPaneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(todayDateJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(senderIdJLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(dateOfPostJLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(statusJlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(postSolPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(postSolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addComponent(postJBtn))
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backJButton2)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout bottomlayeredPaneLayout = new javax.swing.GroupLayout(bottomlayeredPane);
        bottomlayeredPane.setLayout(bottomlayeredPaneLayout);
        bottomlayeredPaneLayout.setHorizontalGroup(
            bottomlayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 803, Short.MAX_VALUE)
            .addGroup(bottomlayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(postSolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bottomlayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(postQueryJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bottomlayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewProposedSolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottomlayeredPaneLayout.setVerticalGroup(
            bottomlayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
            .addGroup(bottomlayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(postSolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bottomlayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(postQueryJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bottomlayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(viewProposedSolPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottomlayeredPane.setLayer(viewProposedSolPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bottomlayeredPane.setLayer(postQueryJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bottomlayeredPane.setLayer(postSolPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bottomlayeredPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dspPostQueryPanelJBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dspSolPanelJBtn)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dspPostQueryPanelJBtn)
                    .addComponent(dspSolPanelJBtn)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(bottomlayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dspSolPanelJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dspSolPanelJBtnActionPerformed
        this.request = null;
        if (studentPortalJTable.getSelectedRow() > -1) {
            postQueryJPanel.setVisible(false);
            postSolPanel.setVisible(true);
            viewProposedSolPanel.setVisible(false);
            populatePriorValue();
        } else {
            JOptionPane.showMessageDialog(null, "Please select query first!");
        }
    }//GEN-LAST:event_dspSolPanelJBtnActionPerformed

    public void populatePriorValue() {
        DefaultTableModel dtm = (DefaultTableModel) studentPortalJTable.getModel();
        int selectedRow = studentPortalJTable.getSelectedRow();
        StudentPortalWorkRequest req = (StudentPortalWorkRequest) dtm.getValueAt(selectedRow, 0);
        subjectSolPaneLabel.setText(req.getMessage());
        senderIdJLbl.setText(req.getSender().getUsername());
        dateOfPostJLbl.setText(String.valueOf(req.getRequestDate()));
        todayDateJLbl.setText(String.valueOf(new Date()));
        statusJlabel.setText(req.getStatus());
        QueryJTxtArea.setText(req.getQuery());
        this.request = req;
    }

    private void dspPostQueryPanelJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dspPostQueryPanelJBtnActionPerformed
        // TODO add your handling code here:
        this.request = null;
        postQueryJPanel.setVisible(true);
        postSolPanel.setVisible(false);
        viewProposedSolPanel.setVisible(false);

    }//GEN-LAST:event_dspPostQueryPanelJBtnActionPerformed

    private void postQueryJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postQueryJBtnActionPerformed
        // TODO add your handling code here:
        if (!inputSubjectJtxt.getText().isEmpty()) {
            StudentPortalWorkRequest studentPortalWorkRequest = new StudentPortalWorkRequest();
            studentPortalWorkRequest.setSender(acc);
            studentPortalWorkRequest.setRequestDate(new Date());
            studentPortalWorkRequest.setMessage(inputSubjectJtxt.getText());
            studentPortalWorkRequest.setQuery(inputQueryJTxt.getText());
            studentPortalWorkRequest.setStatus((String) inputStatusJCombo.getSelectedItem());

            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if ((org instanceof StudentOrganization)) {
                    org.getWorkQueue().getWorkRequestList().add(studentPortalWorkRequest);
                    JOptionPane.showMessageDialog(null, "Query posted!");
                    populatePortalTable();
                    resetPostQuery();
                }
            }//end of for
        } else {
            JOptionPane.showMessageDialog(null, "Please provide details of your Query");
        }
//end of if
    }//GEN-LAST:event_postQueryJBtnActionPerformed

    public void resetPostQuery() {
        inputSubjectJtxt.setText("");
        inputQueryJTxt.setText("");

    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.request = null;
        this.selConversation = null;
        viewProposedSolPanel.setVisible(true);
        postQueryJPanel.setVisible(false);
        postSolPanel.setVisible(false);

        if (studentPortalJTable.getSelectedRow() > -1) {
            DefaultTableModel dtm = (DefaultTableModel) studentPortalJTable.getModel();
            int selectedRow = studentPortalJTable.getSelectedRow();
            StudentPortalWorkRequest req = (StudentPortalWorkRequest) dtm.getValueAt(selectedRow, 0);
            this.request = req;
            populateEvaluationWindow();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void populateEvaluationWindow() {
        DefaultListModel DLM = new DefaultListModel();
        Boolean newNotification = false;
        for (ChatConversation conversation : ((StudentPortalWorkRequest) this.request).getSolDiscussionList()) {
            DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
            String reportDate = df.format(conversation.getDateOfproposal());
            DLM.addElement(conversation.getCoversationId() + " " + reportDate);
            newNotification = true;
        }

        if (newNotification.equals(true)) {
            proposedSolJList.setModel(DLM);
        }

    }

    private void postJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postJBtnActionPerformed
        // TODO add your handling code here:
        if (!solutionJTxtArea.getText().isEmpty()) {
            if (this.request != null) {
                this.request.setCheckedNotification(false);
                ChatConversation conversation = new ChatConversation();
                conversation.setProposedSoln(solutionJTxtArea.getText());
                conversation.setReplierUA(acc);
                conversation.setSenderUA(request.getSender());
                conversation.setDateOfReply(null);
                conversation.setReply("");
                conversation.setImpMark(false);
                conversation.setDateOfproposal(new Date());
                ((StudentPortalWorkRequest) this.request).getSolDiscussionList().add(conversation);
                this.request.setStatus("Solution provided");

                JOptionPane.showMessageDialog(null, "Proposed solution sent!");
                populatePortalTable();
                resetProposedSol();
            } else {
                JOptionPane.showMessageDialog(null, "No request selected to propose solution");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter your proposed solution!");
        }
    }//GEN-LAST:event_postJBtnActionPerformed

    public void resetProposedSol() {
        QueryJTxtArea.setText("");
        solutionJTxtArea.setText("");
        subjectSolPaneLabel.setText("");
        senderIdJLbl.setText("");
        todayDateJLbl.setText("");
        dateOfPostJLbl.setText("");
        statusJlabel.setText("");
    }

    private void proposedSolJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proposedSolJListMouseClicked
        this.selConversation = null;
        if (proposedSolJList.getSelectedValue() != null) {

            String[] part = String.valueOf(proposedSolJList.getSelectedValue()).split(" ");

            for (ChatConversation conversation : ((StudentPortalWorkRequest) this.request).getSolDiscussionList()) {
                DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
                String reportDate = df.format(conversation.getDateOfproposal());

                if ((conversation.getCoversationId().equals(part[0])) && (reportDate.equals(part[1] + " " + part[2]))) {
                    this.selConversation = new ChatConversation();
                    this.selConversation = conversation;

                    evalSubjectJText.setText(this.request.getMessage());
                    if (conversation.getReply().isEmpty()) {
                        evalPropSolJTxtArea.setText(conversation.getReplierUA() + "\t" + conversation.getDateOfproposal() + "\n" + conversation.getProposedSoln());
                    } else {
                        String newSolution = conversation.getProposedSoln();
                        newSolution = newSolution + "\n\n" + conversation.getReplierUA().getUsername() + "\t" + conversation.getDateOfReply() + "\n" + conversation.getReply();
                        evalPropSolJTxtArea.setText(newSolution);
                    }
//                  break;
                } else {
                    JOptionPane.showMessageDialog(null, "No panel match");
                }
            }
        }

    }//GEN-LAST:event_proposedSolJListMouseClicked

    private void evalReplyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evalReplyJButtonActionPerformed
        // TODO add your handling code here:
        if (this.selConversation != null) {
            if (!evalReplyJTxt.getText().isEmpty()) {
                this.selConversation.setReplierUA(acc);
                // this.selConversation.setImpMark(evalImpCheckBox.isSelected());
                this.selConversation.setDateOfReply(new Date());
                this.selConversation.setReply(evalReplyJTxt.getText());
                this.selConversation.setProposedSoln(evalPropSolJTxtArea.getText());
                // this.selConversation.set
                this.request.setStatus("Solution discussion");
                populatePortalTable();
                JOptionPane.showMessageDialog(null, "Response recorded!");
                resetEvaluateFields();
            } else {
                JOptionPane.showMessageDialog(null, "No response provided!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No conversation selected!");
        }
    }//GEN-LAST:event_evalReplyJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton1ActionPerformed

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed

    public void resetEvaluateFields() {

        evalPropSolJTxtArea.setText("");
        evalReplyJTxt.setText("");
        evalSubjectJText.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea QueryJTxtArea;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton backJButton1;
    private javax.swing.JButton backJButton2;
    private javax.swing.JLayeredPane bottomlayeredPane;
    private javax.swing.JLabel dateOfPostJLbl;
    private javax.swing.JLabel datePostJLbl;
    private javax.swing.JButton dspPostQueryPanelJBtn;
    private javax.swing.JButton dspSolPanelJBtn;
    private javax.swing.JTextArea evalPropSolJTxtArea;
    private javax.swing.JButton evalReplyJButton;
    private javax.swing.JTextArea evalReplyJTxt;
    private javax.swing.JTextField evalSubjectJText;
    private javax.swing.JTextArea inputQueryJTxt;
    private javax.swing.JComboBox inputStatusJCombo;
    private javax.swing.JTextField inputSubjectJtxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton postJBtn;
    private javax.swing.JButton postQueryJBtn;
    private javax.swing.JPanel postQueryJPanel;
    private javax.swing.JPanel postSolPanel;
    private javax.swing.JList proposedSolJList;
    private javax.swing.JLabel senderIdJLbl;
    private javax.swing.JTextArea solutionJTxtArea;
    private javax.swing.JLabel statusJlabel;
    private javax.swing.JTable studentPortalJTable;
    private javax.swing.JLabel subjectSolPaneLabel;
    private javax.swing.JLabel todayDateJLbl;
    private javax.swing.JPanel viewProposedSolPanel;
    // End of variables declaration//GEN-END:variables
}
