/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterfaceMain;

import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.Community.StudentOrganization;
import business.Organization.Organization;
import business.Role.StudentRole;
import business.UserAccount.UserAccount;
import business.db4oUtils.DB4OUtil;
import business.ecosystem.Ecosystem;
import business.person.Person;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ilanigam17
 */
public class MainJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame1
     */
    private Ecosystem ecoSystem;
    private UserAccount userAccount;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    public MainJFrame1() {
        super("Adolescent Dilemma's Stimulator");
        initComponents();

        ecoSystem = dB4OUtil.retrieveSystem();

        loginLabel.setText("Welcome to the world of solutions!!");
        loginLabel.setToolTipText("Goto File -> Click Login");
        this.setExtendedState(Frame.MAXIMIZED_BOTH);
        loginJMenu.getMenuComponent(1).setEnabled(false);
        // createSysAdmin();

        jPanel1.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userProcessContainer = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        loginJMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        signUpJMenuItem = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(null);

        loginLabel.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(102, 0, 102));
        loginLabel.setText("Welcome to the world of solutions!!");
        userProcessContainer.add(loginLabel);
        loginLabel.setBounds(52, 64, 780, 130);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setText("SIGN UP for new users");
        jPanel1.add(jLabel5);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("For new user, Please SignIn using below Username/Password:");
        jPanel1.add(jLabel2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setText("Goto Tab \"UserAccount\" ---> Select \"Login\" and Enter following credentials:");
        jPanel1.add(jLabel6);

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Username: student                                                                      ");
        jPanel1.add(jLabel3);

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setText("Password: student                                                                        ");
        jPanel1.add(jLabel7);

        jLayeredPane1.add(jPanel1);
        jPanel1.setBounds(0, 30, 560, 500);

        userProcessContainer.add(jLayeredPane1);
        jLayeredPane1.setBounds(50, 160, 530, 360);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterfaceMain/login.jpg"))); // NOI18N
        userProcessContainer.add(jLabel1);
        jLabel1.setBounds(40, 0, 1360, 750);

        getContentPane().add(userProcessContainer, java.awt.BorderLayout.CENTER);

        loginJMenu.setText("User Account");
        loginJMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJMenuActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Login");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        loginJMenu.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Logoff");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        loginJMenu.add(jMenuItem2);

        jMenuBar1.add(loginJMenu);

        signUpJMenuItem.setText("New User");
        signUpJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpJMenuItemActionPerformed(evt);
            }
        });

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("SignUp");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        signUpJMenuItem.add(jMenuItem3);

        jMenuBar1.add(signUpJMenuItem);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJMenuActionPerformed

    }//GEN-LAST:event_loginJMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        LoginJFrame loginFrame = new LoginJFrame(ecoSystem, this);
        // System.out.println("inside login");
        loginFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.removeAll();
        //LogOutJPanel welcome = new LogOutJPanel(userAccount);
        NewJPanel welcome = new NewJPanel(userAccount);
        userProcessContainer.add("blank", welcome);

        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.next(userProcessContainer);
        dB4OUtil.storeSystem(ecoSystem);
        loginJMenu.getMenuComponent(0).setEnabled(true);
        loginJMenu.getMenuComponent(1).setEnabled(false);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        // customer will signup all the information and send to student organization panel.
        // Student org admin will then approves it based on network.
        // customer will be given username and password via mail, which can then be edited by user. using view and update panel
        jPanel1.setVisible(true);
        loginLabel.setVisible(false);
        signUpJMenuItem.setVisible(false);
        signUp();
        loginJMenu.getMenuComponent(0).setEnabled(false);
        loginJMenu.getMenuComponent(1).setEnabled(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public void signUp() {
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        userAccount = new UserAccount();

        //Step2: Go inside each network to check each enterprise
        for (Network network : ecoSystem.getNetworkList()) {
            //Step 2-a: Check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {

                //Step3: Check against each organization inside that enterprise
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    //userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                    if (organization instanceof StudentOrganization) {
                        inEnterprise = enterprise;
                        inOrganization = organization;
                        userAccount.setUsername("student");
                        userAccount.setPassword("student");
                        userAccount.setRole(new StudentRole());
                        //  userAccount.setPerson(new Person());
                        break;
                    }
                }

                if (inOrganization != null) {
                    break;
                }
            }
            if (inEnterprise != null) {
                break;
            }
        }

        if (userAccount == null) {

            JOptionPane.showMessageDialog(null, "Soory!No Student Organization present yet!");
        } else {
            userProcessContainer.removeAll();
            userProcessContainer.setLayout(new CardLayout());
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            JPanel temp = userAccount.getRole().createWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, ecoSystem);
            userProcessContainer.add("workArea", userAccount.getRole().createWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, ecoSystem));
            layout.next(userProcessContainer);

        }

    }
    private void signUpJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpJMenuItemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_signUpJMenuItemActionPerformed

    public void ReturnAcc(UserAccount acc, Organization inOrganization, Enterprise inEnterprise, Ecosystem system) {
        userAccount = acc;
        //loginLabel.setText("Welcome "+userAccount.getUsername());

        if (userAccount == null) {

            return;
        } else {
            userProcessContainer.removeAll();
            userProcessContainer.setLayout(new CardLayout());
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            JPanel temp = userAccount.getRole().createWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, system);
            userProcessContainer.add("workArea", userAccount.getRole().createWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, system));
            layout.next(userProcessContainer);
            loginJMenu.getMenuComponent(0).setEnabled(false);
            loginJMenu.getMenuComponent(1).setEnabled(true);
            signUpJMenuItem.setVisible(false);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu loginJMenu;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JMenu signUpJMenuItem;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
