/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterfaceMain;

import business.UserAccount.UserAccount;

/**
 *
 * @author ilanigam17
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel(UserAccount acc) {
        initComponents();
        logOutMsgJLbl.setText("Thanks " + acc + " for using this app!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logOutMsgJLbl = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        logOutMsgJLbl.setBackground(new java.awt.Color(0, 0, 0));
        logOutMsgJLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterfaceMain/einsteinquotes.jpg"))); // NOI18N
        jPanel1.add(logOutMsgJLbl, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logOutMsgJLbl;
    // End of variables declaration//GEN-END:variables
}
