/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterfaceMain;

import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.Organization;
import business.ecosystem.Ecosystem;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import userInterface.enterprise.ManageEnterpriseAdminJPanel;
import userInterface.enterprise.ManageEnterpriseJPanel;
import userInterface.network.ManageNetworkJPanel;

/**
 *
 * @author ilanigam17
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Ecosystem system;

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        netJBtn = new javax.swing.JButton();
        entAdminJBtn = new javax.swing.JButton();
        entJBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ecoJTree = new javax.swing.JTree();
        iconCompanyLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        netJBtn.setText("Manage Networks");
        netJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netJBtnActionPerformed(evt);
            }
        });

        entAdminJBtn.setText("Manage Enterprise Admin");
        entAdminJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entAdminJBtnActionPerformed(evt);
            }
        });

        entJBtn.setText("Manage Enterprise");
        entJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entJBtnActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("EcoSystem");
        ecoJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(ecoJTree);

        iconCompanyLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterfaceMain/noworries.jpg"))); // NOI18N
        iconCompanyLbl.setText("iconCompanyLbl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entAdminJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(entJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(netJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(218, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconCompanyLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(netJBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entJBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entAdminJBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconCompanyLbl)
                .addGap(2, 2, 2))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void netJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netJBtnActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer, system);
        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_netJBtnActionPerformed

    private void entJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entJBtnActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseJPanel", manageEnterpriseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_entJBtnActionPerformed

    private void entAdminJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entAdminJBtnActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_entAdminJBtnActionPerformed

    public void populateTree() {
        DefaultTreeModel tree = (DefaultTreeModel) ecoJTree.getModel();

        ArrayList<Network> networkList = system.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization> organizationList;
        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");

        DefaultMutableTreeNode root = (DefaultMutableTreeNode) tree.getRoot();
        root.removeAllChildren();
        root.insert(networks, 0);

        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        for (int i = 0; i < networkList.size(); i++) {
            if (networkList.get(i) != null) {
                networkNode = new DefaultMutableTreeNode(networkList.get(i).getName());
                networks.insert(networkNode, i);

                enterpriseList = networkList.get(i).getEnterpriseDirectory().getEnterpriseList();
                for (int j = 0; j < enterpriseList.size(); j++) {
                    enterpriseNode = new DefaultMutableTreeNode(enterpriseList.get(j).getName());
                    networkNode.insert(enterpriseNode, j);

                    organizationList = enterpriseList.get(j).getOrganizationDirectory().getOrganizationList();
                    for (int k = 0; k < organizationList.size(); k++) {
                        organizationNode = new DefaultMutableTreeNode(organizationList.get(k).getName());
                        enterpriseNode.insert(organizationNode, k);
                    }
                }
            }
        }
        tree.reload();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree ecoJTree;
    private javax.swing.JButton entAdminJBtn;
    private javax.swing.JButton entJBtn;
    private javax.swing.JLabel iconCompanyLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton netJBtn;
    // End of variables declaration//GEN-END:variables
}
