/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.people;

import business.Organization.Organization;
import business.Organization.OrganizationDirectory;
import business.UserAccount.UserAccount;
import business.person.Person;
import business.utils.Validate;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ilanigam17
 */
public class ManagePersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    private OrganizationDirectory organizationDir;

    /**
     * Creates new form ManagePersonJPanel
     */
    public ManagePersonJPanel(JPanel userProcessContainer, OrganizationDirectory directory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = directory;
        
            
            

        populateOrganizationComboBox();
        populateOrganizationEmpComboBox();
    }

    public void populateOrganizationComboBox() {
        organizationJComboBox.removeAllItems();

        for (Organization organization : organizationDir.getOrganizationList()) {
            if (!organization.getName().contains("Student")) {
                organizationJComboBox.addItem(organization);
            }
        }
    }

    public void populateOrganizationEmpComboBox() {
        organizationEmpJComboBox.removeAllItems();

        for (Organization organization : organizationDir.getOrganizationList()) {
            if (!organization.getName().contains("Student")) {
                organizationEmpJComboBox.addItem(organization);
            }
        }
    }

    private void populateTable(Organization organization) {
        DefaultTableModel model = (DefaultTableModel) orgPersonJTable.getModel();

        model.setRowCount(0);

        for (Person person : organization.getPersonDirectory().getPersonList()) {
            Object[] row = new Object[2];
            row[0] = person.getId();
            row[1] = person;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinField1 = new com.toedter.components.JSpinField();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        townJText1 = new javax.swing.JTextField();
        zipJText1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        stAddTextArea1 = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        phNumJText1 = new javax.swing.JTextField();
        organizationJComboBox = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        orgPersonJTable = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        addJButton1 = new javax.swing.JButton();
        removeJBtn2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        organizationEmpJComboBox = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        nameJTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Add Organization Administrators");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        townJText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                townJText1ActionPerformed(evt);
            }
        });

        zipJText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipJText1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Town");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Zip Code");

        jScrollPane3.setPreferredSize(new java.awt.Dimension(174, 96));

        stAddTextArea1.setColumns(40);
        stAddTextArea1.setRows(5);
        jScrollPane3.setViewportView(stAddTextArea1);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Street address");

        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Phone Number");

        orgPersonJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(orgPersonJTable);

        jLabel24.setText("Organization");

        addJButton1.setBackground(new java.awt.Color(204, 255, 255));
        addJButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addJButton1.setText("Create Employee");
        addJButton1.setBorder(null);
        addJButton1.setFocusable(false);
        addJButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addJButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButton1ActionPerformed(evt);
            }
        });

        removeJBtn2.setText("Remove");
        removeJBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJBtn2ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Organization");

        organizationEmpJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationEmpJComboBoxActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(59, 59, 59)
                                .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel20))
                                    .addGap(200, 200, 200)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nameJTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phNumJText1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(organizationEmpJComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel17))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(jLabel18)
                                            .addGap(202, 202, 202)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(townJText1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(zipJText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(addJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeJBtn2)))))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(organizationJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeJBtn2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(organizationEmpJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(nameJTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phNumJText1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel18)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(zipJText1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(townJText1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(addJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void townJText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_townJText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_townJText1ActionPerformed

    private void zipJText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipJText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipJText1ActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed
        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        if (organization != null) {
            populateTable(organization);
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

 public String ValidateProfile() {

        String errMsg = new String();

        if (nameJTextField1.getText().isEmpty()) {
            errMsg = errMsg + "Name is manadatory\n";
        } else {
            if (!nameJTextField1.getText().matches("[a-zA-Z0-9 ]*")) {
                errMsg = errMsg + "Name is not a valid input\n";
            }
        }

        if (stAddTextArea1.getText().isEmpty()) {
            errMsg = errMsg + "Street Address is manadatory\n";
        } else {
            if (!stAddTextArea1.getText().matches("[a-zA-Z_0-9# .-]*")) {
                errMsg = errMsg + "Street Address is not a valid input\n";
            }
        }

        if (townJText1.getText().isEmpty()) {
            errMsg = errMsg + "Town is manadatory\n";
        } else {
            if (!townJText1.getText().matches("[a-zA-Z_0-9]*")) {
                errMsg = errMsg + "Town is not a valid input\n";
            }
        }
        if (zipJText1.getText().isEmpty()) {
            errMsg = errMsg + "Zipcode is manadatory\n";
        } else {
            if (!zipJText1.getText().matches("[0-9]*")) {
                errMsg = errMsg + "Zipcode can only be integer\n";
            }
            if (!(zipJText1.getText().length() == 5)) {
                errMsg = errMsg + "Zip Code should be 5 digits\n";
            }
        }
       
        if (phNumJText1.getText().isEmpty()) {
            errMsg = errMsg + "Phone Number is manadatory\n";
        } else {
            if (!phNumJText1.getText().matches("[0-9]*")) {
                errMsg = errMsg + "Phone number is integer only\n";
            }
            if (!(phNumJText1.getText().length() == 10)) {
                errMsg = errMsg + "Phone number should be 10 digits\n";
            }
        }

        return errMsg;
    }

    
    
    private void addJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButton1ActionPerformed
        Organization organization = (Organization) organizationEmpJComboBox.getSelectedItem();
         String errMsg = "";
        errMsg = ValidateProfile();
        if (errMsg.toString().isEmpty() == true) {
                if (organization != null) {

                    Person person = organization.getPersonDirectory().addPerson();
                    person.setName(nameJTextField1.getText());
                    person.setPhoneNum(Long.valueOf(phNumJText1.getText()));
                   // person.setEmailId(emailJText2.getText());
                    person.setStAddress(stAddTextArea1.getText());
                    person.setTown(townJText1.getText());
                    person.setZipCode(Integer.valueOf(zipJText1.getText()));

                    JOptionPane.showMessageDialog(null, "Person added successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter valid name");
                }
                populateOrganizationComboBox();
                populateOrganizationEmpComboBox();
                nameJTextField1.setText("");
                resetFields();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), errMsg.toString(), "Error Message",
                    JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_addJButton1ActionPerformed

    public void resetFields() {
        nameJTextField1.setText("");
        phNumJText1.setText("");
       // emailJText2.setText("");
        stAddTextArea1.setText("");
        townJText1.setText("");
        zipJText1.setText("");
    }
    private void removeJBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJBtn2ActionPerformed

        // TODO add your handling code here:
        Organization organization = (Organization) organizationJComboBox.getSelectedItem();
        if (orgPersonJTable.getSelectedRow() > -1) {
            DefaultTableModel dtm = (DefaultTableModel) orgPersonJTable.getModel();
            Person selPerson = (Person) dtm.getValueAt(orgPersonJTable.getSelectedRow(), 1);

            for (Person person : organization.getPersonDirectory().getPersonList()) {
                if (person == selPerson) {
                    for (Organization org : organizationDir.getOrganizationList()) {
                        for (UserAccount userAcc : org.getUserAccountDirectory().getUserAccountList()) {
                            if (userAcc.getPerson() == selPerson) {
                                org.getUserAccountDirectory().getUserAccountList().remove(userAcc);
                                break;
                            }
                        }
                    }
                    organization.getPersonDirectory().getPersonList().remove(selPerson);
                }
            }

        }
        populateTable(organization);

    }//GEN-LAST:event_removeJBtn2ActionPerformed

    private void organizationEmpJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationEmpJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationEmpJComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton1;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField nameJTextField1;
    private javax.swing.JTable orgPersonJTable;
    private javax.swing.JComboBox organizationEmpJComboBox;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JTextField phNumJText1;
    private javax.swing.JButton removeJBtn2;
    private javax.swing.JTextArea stAddTextArea1;
    private javax.swing.JTextField townJText1;
    private javax.swing.JTextField zipJText1;
    // End of variables declaration//GEN-END:variables
}
