/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.people;

import business.Organization.Organization;
import business.Organization.OrganizationDirectory;
import business.Role.Role;
import business.UserAccount.UserAccount;
import business.person.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ilanigam17
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    private OrganizationDirectory organizationDir;

    /**
     * Creates new form ManageUserAccountJPanel
     */
    public ManageUserAccountJPanel(JPanel userProcessContainer, OrganizationDirectory directory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = directory;

        populateOrgCombo();
        populateUserAccount();

    }

    public void populateOrgCombo() {
        orgComboBox.removeAllItems();
        for (Organization org : organizationDir.getOrganizationList()) {
            if (!org.getName().contains("Student")) {
                orgComboBox.addItem(org);
            }
        }
    }

    public void populatePersonCombo(Organization org) {
        personJCombox.removeAllItems();
        if (org != null) {
            for (Person person : org.getPersonDirectory().getPersonList()) {
                personJCombox.addItem(person);
            }
        }

    }

    public void populateUserAccount() {
        DefaultTableModel dtm = (DefaultTableModel) userAccountJTable.getModel();
        dtm.setRowCount(0);

        Object row[] = new Object[2];
        for (Organization org : organizationDir.getOrganizationList()) {
            for (UserAccount userAcc : org.getUserAccountDirectory().getUserAccountList()) {
                row[0] = userAcc;
                row[1] = userAcc.getRole();
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userAccountJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orgComboBox = new javax.swing.JComboBox();
        userprofileJtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pwdJField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        personJCombox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        createJBtn = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        roleJComboBox = new javax.swing.JComboBox();
        removeJBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage User Accounts");

        userAccountJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "UserProfile", "Role"
            }
        ));
        jScrollPane1.setViewportView(userAccountJTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Create UserAccount:");

        jLabel3.setText("Organization:");

        orgComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgComboBoxActionPerformed(evt);
            }
        });

        userprofileJtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userprofileJtxtActionPerformed(evt);
            }
        });

        jLabel4.setText("UserProfile name:");

        pwdJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdJFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Password:");

        jLabel6.setText("Employee Name:");

        createJBtn.setText("Create");
        createJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJBtnActionPerformed(evt);
            }
        });

        backJBtn.setText("<<Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Role");

        roleJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleJComboBoxActionPerformed(evt);
            }
        });

        removeJBtn.setText("Remove");
        removeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createJBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2))
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(backJBtn))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(personJCombox, 0, 146, Short.MAX_VALUE)
                                        .addComponent(pwdJField)
                                        .addComponent(userprofileJtxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(orgComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeJBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeJBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(roleJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(orgComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personJCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userprofileJtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdJField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(createJBtn)
                .addGap(18, 18, 18)
                .addComponent(backJBtn)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userprofileJtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userprofileJtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userprofileJtxtActionPerformed

    private void pwdJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdJFieldActionPerformed

    private void createJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJBtnActionPerformed
        // TODO add your handling code here:
        String userName = userprofileJtxt.getText();
        String password = String.valueOf(pwdJField.getPassword());

        if (!userName.isEmpty() && !password.isEmpty() && personJCombox.getSelectedItem() != null && roleJComboBox.getSelectedItem() != null) {
            Organization org = (Organization) orgComboBox.getSelectedItem();
            org.getUserAccountDirectory().createUserAccount(userName, password, (Person) personJCombox.getSelectedItem(), (Role) roleJComboBox.getSelectedItem());
            JOptionPane.showMessageDialog(null, "Profile added successfully");
        } else {
            JOptionPane.showMessageDialog(null, "Please input and select all the fields");
        }

        populateUserAccount();
        populateOrgCombo();
        userprofileJtxt.setText("");
        pwdJField.setText("");
    }//GEN-LAST:event_createJBtnActionPerformed

    private void orgComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgComboBoxActionPerformed
        // TODO add your handling code here:
        if (orgComboBox != null) {
            Organization org = (Organization) orgComboBox.getSelectedItem();
            roleJComboBox.removeAllItems();
            if (org != null) {
                for (Role role : org.getSupportedRole()) {
                    roleJComboBox.addItem(role);
                }
            }
            populatePersonCombo(org);
        }
    }//GEN-LAST:event_orgComboBoxActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void roleJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleJComboBoxActionPerformed

    private void removeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJBtnActionPerformed
        // TODO add your handling code here:
        if (userAccountJTable.getSelectedRow() > -1) {
            DefaultTableModel dtm = (DefaultTableModel) userAccountJTable.getModel();
            UserAccount ua = (UserAccount) dtm.getValueAt(userAccountJTable.getSelectedRow(), 0);
            for (Organization org : organizationDir.getOrganizationList()) {
                for (UserAccount userAcc : org.getUserAccountDirectory().getUserAccountList()) {
                    if (userAcc == ua) {
                        org.getUserAccountDirectory().getUserAccountList().remove(ua);
                        break;
                    }
                }
            }
            populateUserAccount();
        }
    }//GEN-LAST:event_removeJBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton createJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox orgComboBox;
    private javax.swing.JComboBox personJCombox;
    private javax.swing.JPasswordField pwdJField;
    private javax.swing.JButton removeJBtn;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JTable userAccountJTable;
    private javax.swing.JTextField userprofileJtxt;
    // End of variables declaration//GEN-END:variables
}
