/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.teacher;

import business.Enterprise.Enterprise;
import business.Organization.Organization;
import business.Organization.Community.TeacherOrganization;
import business.UserAccount.UserAccount;
import business.WorkQueue.PersonalHealthIssueWorkRequest;
import business.WorkQueue.StudentPortalWorkRequest;
import business.WorkQueue.WorkRequest;
import business.ecosystem.Ecosystem;
import business.person.ProfessionalsProfile;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.badMoodDay.StudentPortalJPanel;
import userInterface.badMoodDay.StudentTeacherMentorPortalJPanel;
import userInterface.healthCare.HealthIssueRequestJPanel;
import userInterface.healthCare.HealthRecordWorkAreaJPanel;

/**
 *
 * @author ilanigam17
 */
public class TeacherEntryWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount acc;
    private Ecosystem ecosystem;
    private Enterprise enterprise;
    private Organization org;
    private ProfessionalsProfile tp;

    /**
     * Creates new form youthEntryWorkAreaJPanrl
     */
    public TeacherEntryWorkAreaJPanel(JPanel userProcessContainer, UserAccount acc, Organization org, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.acc = acc;
        this.enterprise = enterprise;
        this.org = org;

       // System.err.println("acc..........." + acc.getUsername() + "person" + acc.getPerson().getName());
        this.ecosystem = ecosystem;
        notificationScrollPane.setVisible(false);
        populateNotification();

        determineTeacherProfile();
    }

    public void determineTeacherProfile() {
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof TeacherOrganization) {
                for (ProfessionalsProfile teacherProfile : ((TeacherOrganization) org).getTeacherDirectory().getTeacherList()) {
                    if (acc == teacherProfile.getUserAccount()) {
                        this.tp = teacherProfile;
                        jProgressBar1.setValue(100);
                        break;
                    }//
                }//
            }//end if org
        }//end for org
    }

    public void populateNotification() {
        DefaultListModel DLM = new DefaultListModel();
        Boolean newNotification = false;
        for (WorkRequest request : org.getWorkQueue().getWorkRequestList()) {
            try {
                if (request.getStatus().equalsIgnoreCase("completed") && request.getCheckedNotification().equals(false)) {
                    DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
                    String reportDate = df.format(request.getRequestDate());
                    DLM.addElement(request.getId() + "(" + reportDate + ")" + request.getMessage());
                    newNotification = true;
                }

            } catch (Exception e) {
              //  System.err.println("youthEntryWorkAreaJPanel..........." + e);
            }

        }
        if (newNotification.equals(true)) {
            notificationScrollPane.setVisible(true);
            jList1.setModel(DLM);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studenthelpPortalJBtn = new javax.swing.JButton();
        updateVitalRecJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        notificationScrollPane = new javax.swing.JScrollPane();
        notificationJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jProgressBar1 = new javax.swing.JProgressBar();
        updateProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        studenthelpPortalJBtn.setBackground(new java.awt.Color(153, 153, 255));
        studenthelpPortalJBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        studenthelpPortalJBtn.setText("Student help portal!");
        studenthelpPortalJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studenthelpPortalJBtnActionPerformed(evt);
            }
        });

        updateVitalRecJBtn.setBackground(new java.awt.Color(255, 153, 153));
        updateVitalRecJBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateVitalRecJBtn.setText("Update vital record(+)");
        updateVitalRecJBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                updateVitalRecJBtnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateVitalRecJBtnFocusLost(evt);
            }
        });
        updateVitalRecJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVitalRecJBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Hey!! Let's check if somebody needs your help??");

        imgLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilanigam17\\Desktop\\howAreyouCAT.gif")); // NOI18N

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notifications", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        jList1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout notificationJPanelLayout = new javax.swing.GroupLayout(notificationJPanel);
        notificationJPanel.setLayout(notificationJPanelLayout);
        notificationJPanelLayout.setHorizontalGroup(
            notificationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );
        notificationJPanelLayout.setVerticalGroup(
            notificationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        notificationScrollPane.setViewportView(notificationJPanel);

        jProgressBar1.setStringPainted(true);

        updateProfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateProfile.setText("Update Profile");
        updateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(updateVitalRecJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(studenthelpPortalJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(notificationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studenthelpPortalJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateVitalRecJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imgLabel)))
                    .addComponent(notificationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateVitalRecJBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateVitalRecJBtnFocusGained
        // TODO add your handling code here:
        updateVitalRecJBtn.setBackground(Color.YELLOW);
    }//GEN-LAST:event_updateVitalRecJBtnFocusGained

    private void updateVitalRecJBtnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateVitalRecJBtnFocusLost
        // TODO add your handling code here:
        updateVitalRecJBtn.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_updateVitalRecJBtnFocusLost

    private void updateVitalRecJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVitalRecJBtnActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        HealthRecordWorkAreaJPanel healthRecordWorkAreaJPanel = new HealthRecordWorkAreaJPanel(userProcessContainer, acc, enterprise, ecosystem, false);
        userProcessContainer.add("healthRecordWorkAreaJPanel", healthRecordWorkAreaJPanel);
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_updateVitalRecJBtnActionPerformed

    private void studenthelpPortalJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studenthelpPortalJBtnActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        TeacherHelpOfferingPortalJPanel teacherHelpOfferingPortal = new TeacherHelpOfferingPortalJPanel(userProcessContainer, this.tp, acc, enterprise, ecosystem);
        userProcessContainer.add("teacherHelpOfferingPortal", teacherHelpOfferingPortal);
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_studenthelpPortalJBtnActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (jList1.getSelectedValue() != null) {

            String[] parts = String.valueOf(jList1.getSelectedValue()).split("\\(");
            String[] dateRetrive = parts[1].split("\\)");
            int idMatch = Integer.valueOf(parts[0]);

            for (WorkRequest request : acc.getWorkQueue().getWorkRequestList()) {
                DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
                String reportDate = df.format(request.getRequestDate());

                if ((Integer.valueOf(request.getId()) == idMatch) && (reportDate.equals(dateRetrive[0]))) {
                    request.setCheckedNotification(true);
                    if (request instanceof PersonalHealthIssueWorkRequest) {
                        HealthIssueRequestJPanel healthIssueRequestJPanel = new HealthIssueRequestJPanel(userProcessContainer, acc, enterprise, ecosystem);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        userProcessContainer.add("healthIssueRequestJPanel", healthIssueRequestJPanel);
                        layout.next(userProcessContainer);
                    } else if (request instanceof StudentPortalWorkRequest && ((StudentPortalWorkRequest) request).getCourseId().isEmpty()) {
                        StudentPortalJPanel studentPortalJPanel = new StudentPortalJPanel(userProcessContainer, acc, enterprise, ecosystem);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        userProcessContainer.add("studentPortalJPanel", studentPortalJPanel);
                        layout.next(userProcessContainer);
                    } else if (request instanceof StudentPortalWorkRequest && (!((StudentPortalWorkRequest) request).getCourseId().isEmpty())) {
                        StudentTeacherMentorPortalJPanel studentTeacherMentorPortalJPanel = new StudentTeacherMentorPortalJPanel(userProcessContainer, acc, enterprise, ecosystem);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        userProcessContainer.add("studentTeacherMentorPortalJPanel", studentTeacherMentorPortalJPanel);
                        layout.next(userProcessContainer);
                    }
                    break;
                } else {
                    JOptionPane.showMessageDialog(null, "No panel match");
                }
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void updateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileActionPerformed
        // TODO add your handling code here:
        AddTeacherJPanel addTeacherJPanelFromEntry = new AddTeacherJPanel(userProcessContainer, (TeacherOrganization) org, acc, this.tp, enterprise, ecosystem);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("addTeacherJPanelFromEntry", addTeacherJPanelFromEntry);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_updateProfileActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel notificationJPanel;
    private javax.swing.JScrollPane notificationScrollPane;
    private javax.swing.JButton studenthelpPortalJBtn;
    private javax.swing.JButton updateProfile;
    private javax.swing.JButton updateVitalRecJBtn;
    // End of variables declaration//GEN-END:variables
}
