/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.enterprise;

import business.Enterprise.Enterprise;
import business.Enterprise.Enterprise.EnterpriseType;
import business.Network.Network;
import business.ecosystem.Ecosystem;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterfaceMain.SystemAdminWorkAreaJPanel;

/**
 *
 * @author ilanigam17
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    private Ecosystem system;
    private Network network;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public ManageEnterpriseJPanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateEnterprise();
    }

    public void populateEnterprise() {
        DefaultTableModel dtm = (DefaultTableModel) enterpriseJTable.getModel();
        dtm.setRowCount(0);

        Object row[] = new Object[3];
        for (Network nw : system.getNetworkList()) {
            if (nw != null) {
                for (Enterprise ent : nw.getEnterpriseDirectory().getEnterpriseList()) {
                    row[1] = nw.getName();
                    row[0] = ent.getName();
                    row[2] = ent.getEnterpriseType();
                    dtm.addRow(row);
                }
            }
        }

        populateNetworkCombo();
        populateEntTypeCombo();
    }

    public void populateNetworkCombo() {
        DefaultComboBoxModel dcbm = (DefaultComboBoxModel) nwJCombox.getModel();
        nwJCombox.removeAllItems();

        for (Network nw : system.getNetworkList()) {
            nwJCombox.addItem(nw);
        }

    }

    public void populateEntTypeCombo() {
        DefaultComboBoxModel dcbm = (DefaultComboBoxModel) entTypeJCombox.getModel();
        entTypeJCombox.removeAllItems();
        entTypeJCombox.addItem(Enterprise.EnterpriseType.COMMUNITY);
        entTypeJCombox.addItem(Enterprise.EnterpriseType.FINANCE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        enterpriseJTxt = new javax.swing.JTextField();
        submitEnterpriseJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nwJCombox = new javax.swing.JComboBox();
        entTypeJCombox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network Name", "Type"
            }
        ));
        jScrollPane1.setViewportView(enterpriseJTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Enterprise");

        enterpriseJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseJTxtActionPerformed(evt);
            }
        });

        submitEnterpriseJBtn.setText("Submit");
        submitEnterpriseJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEnterpriseJBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Enterprise Name:");

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        entTypeJCombox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entTypeJComboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Select Network:");

        jLabel4.setText("Select Ent. Type:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Create Enterprise:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(entTypeJCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(enterpriseJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(submitEnterpriseJBtn))
                                    .addComponent(nwJCombox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nwJCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(entTypeJCombox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitEnterpriseJBtn)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitEnterpriseJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEnterpriseJBtnActionPerformed
        // TODO add your handling code here:
        if (!enterpriseJTxt.getText().isEmpty()) {
            Network selectedNetwork = (Network) nwJCombox.getSelectedItem();
            if (selectedNetwork != null) {
                Boolean flag = false;
                for (Enterprise ent : selectedNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                    if (ent.getName().equalsIgnoreCase(enterpriseJTxt.getText())) {
                        flag = true;
                        break;
                    }
                }
                if (flag == false) {
                    selectedNetwork.getEnterpriseDirectory().createAndAddEnterprise(enterpriseJTxt.getText(), (EnterpriseType) entTypeJCombox.getSelectedItem());
                    JOptionPane.showMessageDialog(null, "Enterprise added successfully!");
                } else {
                    JOptionPane.showMessageDialog(null, "Enterprise already exist!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please selected Network!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter enterprise name!");
        }
        populateEnterprise();
        populateNetworkCombo();
        populateEnterprise();
        enterpriseJTxt.setText("");
    }//GEN-LAST:event_submitEnterpriseJBtnActionPerformed

    private void enterpriseJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseJTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void entTypeJComboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entTypeJComboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_entTypeJComboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox entTypeJCombox;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JTextField enterpriseJTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox nwJCombox;
    private javax.swing.JButton submitEnterpriseJBtn;
    // End of variables declaration//GEN-END:variables
}
