/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.youthEntry;

import business.Enterprise.CommunityEnterprise;
import business.Enterprise.Enterprise;
import business.Enterprise.FinancialEnterprise;
import business.Network.Network;
import business.Organization.Organization;
import business.Organization.Community.StudentOrganization;
import business.Role.StudentRole;
import business.UserAccount.UserAccount;
import business.ecosystem.Ecosystem;
import business.person.Person;
import business.person.PersonDirectory;
import business.utils.AgeCalculator;
import business.utils.MyPainter;
import business.utils.Validate;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIDefaults;

/**
 *
 * @author ilanigam17
 */
public class AddPersonJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private PersonDirectory personDir;
    private Ecosystem ecosystem;
    private Person personProfile;
    private String newPersonPwd;
    private UserAccount useracc;
    private Organization org;
    private Enterprise enterprise;

    /**
     * Creates new form AddDonorJPanel
     */
    public AddPersonJPanel(JPanel userProcessContainer, PersonDirectory personDir, Ecosystem system, Enterprise ent, UserAccount fromStudentPanelUA) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDir = personDir;
        this.ecosystem = system;
        this.personProfile = null;
        this.useracc = null;
        this.org = null;
        this.enterprise = null;
        if (fromStudentPanelUA != null) {
            addJBtn.setVisible(false);
            continueJBtn.setVisible(true);
            saveJbtn.setEnabled(false);
            updateJBtn.setEnabled(true);
            this.useracc = fromStudentPanelUA;
            this.enterprise = ent;
            populateIndividualDetail();
            createUAJBtn.setVisible(false);
            disablePerson();
            disableUserAccount();
            nwCombo.setVisible(false);
            enterpriseCombo.setVisible(false);
            countryLabel.setVisible(false);
            communityLabel.setVisible(false);
            pwsStrengthJPanel.setVisible(false);
        } else {
            createUAJPanel.setVisible(false);
            pwsStrengthJPanel.setVisible(false);
            saveJbtn.setVisible(false);
            updateJBtn.setVisible(false);
        }
        populateNetwork();
    }

    public void populateNetwork() {
        nwCombo.removeAllItems();
        for (Network nw : ecosystem.getNetworkList()) {
            nwCombo.addItem(nw);
        }
    }

    public void populateEnterprise(Network nw) {
        enterpriseCombo.removeAllItems();
        for (Enterprise entr : nw.getEnterpriseDirectory().getEnterpriseList()) {
            if (entr instanceof CommunityEnterprise) {
                enterpriseCombo.addItem(entr);
            }
        }
    }

    public void populateIndividualDetail() {

        usernameJtxt.setText(useracc.getUsername());
        pwdJtxt1.setText(useracc.getPassword());

        dobJTxt.setDate(useracc.getPerson().getDob());
        emailJText1.setText(useracc.getPerson().getEmailId());
        personNameJTxt.setText(useracc.getPerson().getName());
        // idJText.setText("");
        stAddTextArea.setText(useracc.getPerson().getStAddress());
        townJText.setText(useracc.getPerson().getTown());
        zipJText.setText(String.valueOf(useracc.getPerson().getZipCode()));
        familyIncomeMonJTxt.setText(String.valueOf(useracc.getPerson().getFundsAvail().getFamilyMonIncome()));
        occuJText.setText(useracc.getPerson().getOccupation());
        areaCdeJText.setText(String.valueOf(useracc.getPerson().getAreaCde()));
        phNumJText.setText(String.valueOf(useracc.getPerson().getPhoneNum()));
        gpatxt.setText(String.valueOf(useracc.getPerson().getGpa()));
        schoolJTxt.setText(useracc.getPerson().getSchoolName());
        familyExpMonJTxt.setText(String.valueOf(useracc.getPerson().getFundsAvail().getFamilyMonExpense()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        addJBtn = new javax.swing.JButton();
        townJText = new javax.swing.JTextField();
        zipJText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        familyIncomeMonJTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        occuJText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        areaCdeJText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        phNumJText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stAddTextArea = new javax.swing.JTextArea();
        personNameJTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        nwCombo = new javax.swing.JComboBox();
        communityLabel = new javax.swing.JLabel();
        enterpriseCombo = new javax.swing.JComboBox();
        schoolJTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gpatxt = new javax.swing.JTextField();
        dobJTxt = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        emailJText1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        familyExpMonJTxt = new javax.swing.JTextField();
        pwsStrengthJPanel = new javax.swing.JPanel();
        pwdProgressBar = new javax.swing.JProgressBar();
        jLabel21 = new javax.swing.JLabel();
        pwdStrengthText = new javax.swing.JLabel();
        createUAJPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        createUAJBtn = new javax.swing.JButton();
        usernameJtxt = new javax.swing.JTextField();
        continueJBtn = new javax.swing.JButton();
        pwdJtxt1 = new javax.swing.JPasswordField();
        saveJbtn = new javax.swing.JButton();
        updateJBtn = new javax.swing.JButton();

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Add a Person");

        addJBtn.setText("Add");
        addJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJBtnActionPerformed(evt);
            }
        });

        townJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                townJTextActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Town");

        familyIncomeMonJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyIncomeMonJTxtActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Zip Code");

        occuJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occuJTextActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Email Address");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Occupation");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Area code(Ph Num) ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Phone Number");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Street address");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Name");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(174, 96));

        stAddTextArea.setColumns(40);
        stAddTextArea.setRows(5);
        jScrollPane1.setViewportView(stAddTextArea);

        personNameJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personNameJTxtActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterfaceMain/specGal.jpg"))); // NOI18N

        countryLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        countryLabel.setText("Country");

        nwCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nwComboActionPerformed(evt);
            }
        });

        communityLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        communityLabel.setText("Community");

        enterpriseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseComboActionPerformed(evt);
            }
        });

        schoolJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolJTxtActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("School");

        jLabel4.setText("GPA");

        gpatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gpatxtActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Date of Birth");

        jLabel19.setText("Family Funds: ");

        emailJText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJText1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Family Expense:");

        familyExpMonJTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyExpMonJTxtActionPerformed(evt);
            }
        });

        pwsStrengthJPanel.setBackground(new java.awt.Color(255, 255, 255));
        pwsStrengthJPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pwdProgressBar.setForeground(new java.awt.Color(153, 153, 255));
        pwdProgressBar.setBorderPainted(false);
        pwdProgressBar.setStringPainted(true);
        pwdProgressBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdProgressBarKeyReleased(evt);
            }
        });

        jLabel21.setText("Password Strength:");

        pwdStrengthText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pwdStrengthText.setText("Password Strength");

        javax.swing.GroupLayout pwsStrengthJPanelLayout = new javax.swing.GroupLayout(pwsStrengthJPanel);
        pwsStrengthJPanel.setLayout(pwsStrengthJPanelLayout);
        pwsStrengthJPanelLayout.setHorizontalGroup(
            pwsStrengthJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pwsStrengthJPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pwsStrengthJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pwdProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pwdStrengthText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pwsStrengthJPanelLayout.setVerticalGroup(
            pwsStrengthJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pwsStrengthJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwdProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwdStrengthText)
                .addGap(19, 19, 19))
        );

        createUAJPanel.setBackground(new java.awt.Color(255, 255, 255));
        createUAJPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("UserName");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Password ");
        jLabel17.setToolTipText("Your password strength depends on: # a digit must occur at least once # a lower case letter must occur at least once # an upper case letter must occur at least once # a special character must occur at least once # no whitespace allowed in the entire string # anything, at least eight places though");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Create User Account:");

        createUAJBtn.setText("Create User Account");
        createUAJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUAJBtnActionPerformed(evt);
            }
        });

        usernameJtxt.setColumns(20);
        usernameJtxt.setToolTipText("User name has to be unique");
        usernameJtxt.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                usernameJtxtComponentShown(evt);
            }
        });
        usernameJtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameJtxtActionPerformed(evt);
            }
        });

        continueJBtn.setBackground(new java.awt.Color(102, 255, 102));
        continueJBtn.setText("Continue >>");
        continueJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueJBtnActionPerformed(evt);
            }
        });

        pwdJtxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pwdJtxt1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout createUAJPanelLayout = new javax.swing.GroupLayout(createUAJPanel);
        createUAJPanel.setLayout(createUAJPanelLayout);
        createUAJPanelLayout.setHorizontalGroup(
            createUAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUAJPanelLayout.createSequentialGroup()
                .addGroup(createUAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createUAJPanelLayout.createSequentialGroup()
                        .addGroup(createUAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(createUAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameJtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(pwdJtxt1)))
                    .addGroup(createUAJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 251, Short.MAX_VALUE))
                    .addGroup(createUAJPanelLayout.createSequentialGroup()
                        .addComponent(continueJBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createUAJBtn)))
                .addContainerGap())
        );
        createUAJPanelLayout.setVerticalGroup(
            createUAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createUAJPanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createUAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameJtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createUAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(pwdJtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createUAJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continueJBtn)
                    .addComponent(createUAJBtn))
                .addGap(76, 76, 76))
        );

        saveJbtn.setText("Save");
        saveJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJbtnActionPerformed(evt);
            }
        });

        updateJBtn.setText("Update");
        updateJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createUAJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pwsStrengthJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addComponent(updateJBtn)
                                .addGap(40, 40, 40)
                                .addComponent(saveJbtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addJBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel8)
                                            .addComponent(countryLabel)
                                            .addComponent(communityLabel))
                                        .addGap(143, 143, 143)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(areaCdeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(phNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dobJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(personNameJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailJText1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(occuJText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nwCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(enterpriseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(familyIncomeMonJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(townJText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(gpatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(familyExpMonJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(schoolJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(zipJText, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personNameJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dobJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(familyIncomeMonJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(familyExpMonJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gpatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaCdeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailJText1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(occuJText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(schoolJTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipJText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(townJText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(countryLabel)
                            .addComponent(nwCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pwsStrengthJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateJBtn)
                            .addComponent(saveJbtn))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enterpriseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(communityLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addJBtn)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(createUAJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19)))
                .addGap(159, 159, 159))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJBtnActionPerformed

        String errMsg = "";
        String zipCodePattern = "\\d{5}(-\\d{4})?";
        errMsg = ValidateProfile();
        if (errMsg.toString().isEmpty() == true) {

            Enterprise ent = (Enterprise) enterpriseCombo.getSelectedItem();
            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof StudentOrganization) {
                    this.personProfile = org.getPersonDirectory().addPerson();
                    createNewProfile(personProfile);

                  //  System.err.println("personProfile......." + personProfile.getName());
                    JOptionPane.showMessageDialog(null, "Your profile has been created " + personNameJTxt.getText() + "! \n Now go ahead and create your UserAccount!", "Congratulations!!", JOptionPane.INFORMATION_MESSAGE);
                    createUAJPanel.setVisible(true);
                    pwsStrengthJPanel.setVisible(true);
                    continueJBtn.setVisible(false);
                    this.enterprise = ent;
                    this.org = org;
                    disablePerson();
                    saveJbtn.setVisible(true);
                    updateJBtn.setVisible(true);
                }
            }
            // resetPerson();
            addJBtn.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(new JFrame(), errMsg.toString(), "Error Message",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_addJBtnActionPerformed

    public void createNewProfile(Person person) {
        person.setName(personNameJTxt.getText());
        //person.setPatientID(idJText.getText());
        person.setStAddress(stAddTextArea.getText());
        person.setEmailId(emailJText1.getText());
        person.setTown(townJText.getText());
        person.setZipCode(Integer.valueOf(zipJText.getText()));
        person.setOccupation(occuJText.getText());
        person.setAreaCde(Integer.valueOf(areaCdeJText.getText()));
        person.setPhoneNum(Long.valueOf(phNumJText.getText()));
        person.setSchoolName(schoolJTxt.getText());
        person.setGpa(Float.valueOf(gpatxt.getText()));
        person.setDob(dobJTxt.getDate());
        person.setAge(AgeCalculator.calculateAge(dobJTxt.getDate()));
        if (!familyExpMonJTxt.getText().isEmpty()) {
            person.getFundsAvail().setFamilyMonExpense(Float.valueOf(familyExpMonJTxt.getText()));
        }
        if (!familyIncomeMonJTxt.getText().isEmpty()) {
            person.getFundsAvail().setFamilyMonIncome(Float.valueOf(familyIncomeMonJTxt.getText()));
        }

    }

    public void disableUserAccount() {
        usernameJtxt.setEditable(false);
        pwdJtxt1.setEditable(false);
    }

    public void disablePerson() {
        personNameJTxt.setEditable(false);
        // idJText.setText("");
        stAddTextArea.setEditable(false);
        townJText.setEditable(false);
        zipJText.setEditable(false);
        familyIncomeMonJTxt.setEditable(false);
        occuJText.setEditable(false);
        areaCdeJText.setEditable(false);
        phNumJText.setEditable(false);
        gpatxt.setEditable(false);
        schoolJTxt.setEditable(false);
        familyExpMonJTxt.setEditable(false);
        dobJTxt.setEnabled(false);
    }

    public void enableEditing() {
        personNameJTxt.setEditable(false);
        // idJText.setText("");
        stAddTextArea.setEditable(true);
        townJText.setEditable(true);
        zipJText.setEditable(true);
        familyIncomeMonJTxt.setEditable(true);
        occuJText.setEditable(true);
        areaCdeJText.setEditable(true);
        phNumJText.setEditable(true);
        gpatxt.setEditable(true);
        schoolJTxt.setEditable(true);
        familyExpMonJTxt.setEditable(true);
        dobJTxt.setEnabled(true);
    }

    public String ValidateProfile() {

        String errMsg = new String();
        if ((nwCombo.getSelectedItem() == null || enterpriseCombo.getSelectedItem() == null) && usernameJtxt.getText().isEmpty()) {
            errMsg = errMsg + "No Country and community is associated with current personnel\n";
            return (errMsg).trim();
        }

        if (personNameJTxt.getText().isEmpty()) {
            errMsg = errMsg + "Name is manadatory\n";
        } else {
            if (!personNameJTxt.getText().matches("[a-zA-Z ]*")) {
                errMsg = errMsg + "Name is not a valid input\n";
            }
        }

        if (dobJTxt.getDate() == null) {
            errMsg = errMsg + "Date of Birth is either empty or invalid\n";
        } else {
            if (dobJTxt.getDate().after(new Date())) {
                errMsg = errMsg + "Date of Birth cannot be future date\n";
            } else if (AgeCalculator.calculateAge(dobJTxt.getDate()) <= 2) {
                errMsg = errMsg + "Date of Birth suggests you are younger than 2years, we dont support age<3years \n";
            }
        }

        if (!Validate.ValidateFloat(familyExpMonJTxt.getText(), null)) {
            errMsg = errMsg + "Family Monthly Expenses should be non-negative numberic\n";
        }

        if (!Validate.ValidateFloat(familyIncomeMonJTxt.getText(), null)) {
            errMsg = errMsg + "Family Monthly Income should be non-negative numberic\n";
        }

        if (!Validate.ValidateEmpty(gpatxt.getText(), null)) {
            errMsg = errMsg + "GPA is manadatory\n";
        } else if (!Validate.ValidateFloat(gpatxt.getText(), null)) {
            errMsg = errMsg + "GPA should be Numberic\n";
        }else if ((Float.valueOf(gpatxt.getText())>4) || (Float.valueOf(gpatxt.getText())<0)){
            errMsg = errMsg + "GPA should not be more than 4\n";
        }

        if (stAddTextArea.getText().isEmpty()) {
            errMsg = errMsg + "Street Address is manadatory\n";
        }
        if (townJText.getText().isEmpty()) {
            errMsg = errMsg + "Town is manadatory\n";
        } else {
            if (!townJText.getText().matches("[a-zA-Z_0-9]*")) {
                errMsg = errMsg + "Town is not a valid input\n";
            }
        }
        if (zipJText.getText().isEmpty()) {
            errMsg = errMsg + "Zipcode is manadatory\n";
        } else {
            if (!zipJText.getText().matches("\\d{5}(-\\\\d{4})?")) {
                errMsg = errMsg + "Zipcode can valid 5 digit US Zipcode\n";
            }
            if (!(zipJText.getText().length() == 5)) {
                errMsg = errMsg + "Zip Code should be 5 digits\n";
            }
        }
        if (emailJText1.getText().isEmpty()) {
            errMsg = errMsg + "Email is manadatory\n";
        } else {
            if (!Validate.ValidateEmail(emailJText1.getText(), null)) {
                errMsg = errMsg + "Email is not valid\n";
            }
        }

        if (occuJText.getText().isEmpty()) {
            errMsg = errMsg + "Occupation is manadatory\n";
        }

        if (areaCdeJText.getText().isEmpty()) {
            errMsg = errMsg + "Area code is manadatory\n";
        } else {
            if (!areaCdeJText.getText().matches("[0-9]*")) {
                errMsg = errMsg + "Area code is integer only\n";
            }
            if (!(areaCdeJText.getText().length() == 3)) {
                errMsg = errMsg + "Area code should be 3 digits\n";
            }
        }
        if (phNumJText.getText().isEmpty()) {
            errMsg = errMsg + "Phone Number is manadatory";
        } else {
            if (!phNumJText.getText().matches("[0-9]*")) {
                errMsg = errMsg + "Phone number is integer only\n";
            }
            if (!(phNumJText.getText().length() == 10)) {
                errMsg = errMsg + "Phone number should be 10 digits\n";
            }else if(Long.valueOf(phNumJText.getText())<1000000000){
                 errMsg = errMsg + "Phone number is not valid\n";
            }
        }

        return errMsg;
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void townJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_townJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_townJTextActionPerformed

    private void familyIncomeMonJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyIncomeMonJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_familyIncomeMonJTxtActionPerformed

    private void occuJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occuJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occuJTextActionPerformed

    private void personNameJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personNameJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personNameJTxtActionPerformed

    private void usernameJtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameJtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameJtxtActionPerformed

    public void progressbar(Color ping) {

        UIDefaults defaults = new UIDefaults();
        defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(ping));
        defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(ping));

        pwdProgressBar.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
        pwdProgressBar.putClientProperty("Nimbus.Overrides", defaults);
    }
    private void createUAJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUAJBtnActionPerformed
        // TODO add your handling code here:
        char[] passwordCharArray = pwdJtxt1.getPassword();
        String password = String.valueOf(passwordCharArray);
        if (Validate.ValidateEmpty(password, "Password is manadatory") && Validate.ValidateEmpty(usernameJtxt.getText(), "Username is manadatory")) {
            String pwdStrength = Validate.passwordStrengthCheck(usernameJtxt.getText(), password);

            if (Integer.valueOf(pwdStrength) < 15) {
                pwdProgressBar.setValue(Integer.valueOf(pwdStrength));
                progressbar(Color.RED);
                JOptionPane.showMessageDialog(null, "Password is very weak!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Enterprise ent = (Enterprise) enterpriseCombo.getSelectedItem();
                for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (org instanceof StudentOrganization) {
                        if (org.getUserAccountDirectory().checkIfUsernameIsUnique(usernameJtxt.getText())) {
                            // System.err.println("useracc person before......."+this.personProfile.getName());
                            UserAccount acc = org.getUserAccountDirectory().createUserAccount(usernameJtxt.getText(), password, this.personProfile, (StudentRole) org.getSupportedRole().get(0));
                            //System.err.println("useracc person......."+acc.getPerson().getName());
                            CheckAddFinanciallyStruckPeople(acc);

                            JOptionPane.showMessageDialog(null, "Welcome aboard " + usernameJtxt.getText() + " !", "Congratulations!!", JOptionPane.INFORMATION_MESSAGE);
                            disableUserAccount();
                            this.useracc = acc;
                            continueJBtn.setVisible(true);

                            manageLoginMenu();
                        } else {
                            JOptionPane.showMessageDialog(null, "Username already exsist, Please try something else!", "Abort!!", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_createUAJBtnActionPerformed
    public void manageLoginMenu() {
        // signUpJMenuItem.setVisible(false);
    }

    public void CheckAddFinanciallyStruckPeople(UserAccount acc) {
        for (Network nw : ecosystem.getNetworkList()) {
            if (nw.equals((Network) nwCombo.getSelectedItem())) {
                for (Enterprise ent : nw.getEnterpriseDirectory().getEnterpriseList()) {
                    if (ent instanceof FinancialEnterprise) {
                        float minMonWage = ((FinancialEnterprise) ent).getMinimumWage();
                        if ((!familyIncomeMonJTxt.getText().isEmpty()) && minMonWage > 0) {
                            if (minMonWage > Float.valueOf(familyIncomeMonJTxt.getText())) {
                                ((FinancialEnterprise) ent).getFinancialChallengedDirectory().addUserAccount(acc);
                            }
                        }
                    }
                }
            }
        }
    }
    private void enterpriseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseComboActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_enterpriseComboActionPerformed

    private void nwComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nwComboActionPerformed
        // TODO add your handling code here:
        if (nwCombo.getSelectedItem() != null) {
            populateEnterprise((Network) nwCombo.getSelectedItem());
        }
    }//GEN-LAST:event_nwComboActionPerformed

    private void schoolJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolJTxtActionPerformed

    private void emailJText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJText1ActionPerformed

    private void familyExpMonJTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyExpMonJTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_familyExpMonJTxtActionPerformed

    private void gpatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gpatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gpatxtActionPerformed

    private void pwdProgressBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdProgressBarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdProgressBarKeyReleased

    private void continueJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueJBtnActionPerformed
        // TODO add your handling code here:
       
        YouthEntryWorkAreaJPanel youthEntryWorkAreaJPanel = new YouthEntryWorkAreaJPanel(userProcessContainer, this.useracc, this.enterprise, ecosystem);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("youthEntryWorkAreaJPanel", youthEntryWorkAreaJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_continueJBtnActionPerformed

    private void updateJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJBtnActionPerformed
        // TODO add your handling code here:
        enableEditing();
        if (pwdJtxt1.getPassword().toString() != null) {
            pwdJtxt1.setEditable(true);
            updateJBtn.setEnabled(false);
        }

        saveJbtn.setEnabled(true);
    }//GEN-LAST:event_updateJBtnActionPerformed

    private void saveJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJbtnActionPerformed
        // TODO add your handling code here:
        useracc.setPassword(pwdJtxt1.getPassword().toString());
        String errMsg = "";
        errMsg = ValidateProfile();
        if (errMsg.toString().isEmpty() == true) {
            createNewProfile(this.useracc.getPerson());
            updateJBtn.setEnabled(true);
            saveJbtn.setEnabled(false);
            JOptionPane.showMessageDialog(new JFrame(), "Profile updated Successfully!", "Information Message",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(new JFrame(), errMsg.toString(), "Error Message",
                    JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_saveJbtnActionPerformed

    private void usernameJtxtComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_usernameJtxtComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameJtxtComponentShown

    private void pwdJtxt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdJtxt1KeyReleased
        // TODO add your handling code here:
        char[] pwdList=pwdJtxt1.getPassword();
        String pwd= String.valueOf(pwdList);
        String pwdStrength = Validate.passwordStrengthCheck(usernameJtxt.getText(), pwd);
        int pwdStrengthInt = Integer.valueOf(pwdStrength);
        if (pwdStrengthInt < 15) {
            pwdProgressBar.setValue(Integer.valueOf(pwdStrength));
            progressbar(Color.RED);
            pwdStrengthText.setText("VERY WEAK");
            pwdStrengthText.setForeground(Color.red);
        } else if (pwdStrengthInt < 50) {
            pwdProgressBar.setValue(Integer.valueOf(pwdStrength));
            progressbar(Color.ORANGE);
            pwdStrengthText.setText("WEAK");
            pwdStrengthText.setForeground(Color.ORANGE);
        } else if (pwdStrengthInt < 85) {
            pwdProgressBar.setValue(Integer.valueOf(pwdStrength));
            progressbar(Color.green);
            pwdStrengthText.setText("MEDIUM");
            pwdStrengthText.setForeground(Color.green);
        } else if (pwdStrengthInt <= 100) {
            pwdProgressBar.setValue(Integer.valueOf(pwdStrength));
            progressbar(new Color(0, 127, 82));
            pwdStrengthText.setText("STRONG");
            pwdStrengthText.setForeground(new Color(0, 127, 82));
        }
    }//GEN-LAST:event_pwdJtxt1KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJBtn;
    private javax.swing.JTextField areaCdeJText;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel communityLabel;
    private javax.swing.JButton continueJBtn;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JButton createUAJBtn;
    private javax.swing.JPanel createUAJPanel;
    private com.toedter.calendar.JDateChooser dobJTxt;
    private javax.swing.JTextField emailJText1;
    private javax.swing.JComboBox enterpriseCombo;
    private javax.swing.JTextField familyExpMonJTxt;
    private javax.swing.JTextField familyIncomeMonJTxt;
    private javax.swing.JTextField gpatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox nwCombo;
    private javax.swing.JTextField occuJText;
    private javax.swing.JTextField personNameJTxt;
    private javax.swing.JTextField phNumJText;
    private javax.swing.JPasswordField pwdJtxt1;
    private javax.swing.JProgressBar pwdProgressBar;
    private javax.swing.JLabel pwdStrengthText;
    private javax.swing.JPanel pwsStrengthJPanel;
    private javax.swing.JButton saveJbtn;
    private javax.swing.JTextField schoolJTxt;
    private javax.swing.JTextArea stAddTextArea;
    private javax.swing.JTextField townJText;
    private javax.swing.JButton updateJBtn;
    private javax.swing.JTextField usernameJtxt;
    private javax.swing.JTextField zipJText;
    // End of variables declaration//GEN-END:variables
}
