/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.youthEntry;

import business.Enterprise.Enterprise;
import business.Organization.Community.StudentOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.FinancialWorkRequest;
import business.WorkQueue.PersonalHealthIssueWorkRequest;
import business.WorkQueue.StudentPortalWorkRequest;
import business.WorkQueue.WorkRequest;
import business.ecosystem.Ecosystem;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static userInterface.badMoodDay.FullScreenVideo.showVideo;
import userInterface.badMoodDay.StudentPortalJPanel;
import userInterface.badMoodDay.StudentSanctionFinanceJPanel;
import userInterface.badMoodDay.StudentTeacherMentorPortalJPanel;
import userInterface.healthCare.HealthIssueRequestJPanel;
import userInterface.healthCare.HealthRecordWorkAreaJPanel;
import userInterface.moodSwings.MoodSwingsWorkAreaJPanel;

/**
 *
 * @author ilanigam17
 */
public class YouthEntryWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount acc;
    private Ecosystem ecosystem;
    private Enterprise enterprise;

    /**
     * Creates new form youthEntryWorkAreaJPanrl
     */
    public YouthEntryWorkAreaJPanel(JPanel userProcessContainer, UserAccount acc, Enterprise enterprise, Ecosystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.acc = acc;
        this.enterprise = enterprise;

        //System.err.println("acc..........." + acc.getUsername() + "person" + acc.getPerson().getName());
        this.ecosystem = ecosystem;
        notificationScrollPane.setVisible(false);
        populateNotification();

    }

    public void populateNotification() {
        DefaultListModel DLM = new DefaultListModel();
        Boolean newNotification = false;
        for (WorkRequest request : acc.getWorkQueue().getWorkRequestList()) {
            try {

                //  System.out.println("youth............"+request.getMessage()+"req notifiation....."+request.getCheckedNotification());
                if (request.getCheckedNotification().equals(false)) {
                    DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
                    String reportDate = df.format(request.getRequestDate());
                    DLM.addElement(request.getId() + "(" + reportDate + ")" + request.getMessage() + " request completed");
                    newNotification = true;
                }

            } catch (Exception e) {
                //      System.err.println("youthEntryWorkAreaJPanel..........."+e);
            }

        }
        if (newNotification.equals(true)) {
            notificationScrollPane.setVisible(true);
            jList1.setModel(DLM);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moodSwingJBtn = new javax.swing.JButton();
        updateVitalRecJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        notificationScrollPane = new javax.swing.JScrollPane();
        notificationJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        checkAppointments = new javax.swing.JLabel();
        viewSanctionsJBtn = new javax.swing.JLabel();
        HelpStudPortalJBtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        moodSwingJBtn.setBackground(new java.awt.Color(153, 153, 255));
        moodSwingJBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        moodSwingJBtn.setText("Mood Swings??");
        moodSwingJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodSwingJBtnActionPerformed(evt);
            }
        });

        updateVitalRecJBtn.setBackground(new java.awt.Color(255, 153, 153));
        updateVitalRecJBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateVitalRecJBtn.setText("Update vital record(+)");
        updateVitalRecJBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                updateVitalRecJBtnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                updateVitalRecJBtnFocusLost(evt);
            }
        });
        updateVitalRecJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateVitalRecJBtnActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Hey!! Let's check if you are having mood swings today??");

        imgLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilanigam17\\Desktop\\howAreyouCAT.gif")); // NOI18N

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notifications", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N
        jList1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout notificationJPanelLayout = new javax.swing.GroupLayout(notificationJPanel);
        notificationJPanel.setLayout(notificationJPanelLayout);
        notificationJPanelLayout.setHorizontalGroup(
            notificationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
        notificationJPanelLayout.setVerticalGroup(
            notificationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        notificationScrollPane.setViewportView(notificationJPanel);

        checkAppointments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Financial2.png"))); // NOI18N
        checkAppointments.setText("Fin");
        checkAppointments.setToolTipText("View Appointments");
        checkAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkAppointmentsMouseClicked(evt);
            }
        });

        viewSanctionsJBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/financeImg.jpg"))); // NOI18N
        viewSanctionsJBtn.setText("App");
        viewSanctionsJBtn.setToolTipText("View sactioned finances");
        viewSanctionsJBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewSanctionsJBtnMouseClicked(evt);
            }
        });

        HelpStudPortalJBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/help-blog.png"))); // NOI18N
        HelpStudPortalJBtn.setText("Help");
        HelpStudPortalJBtn.setToolTipText("Help your friends");
        HelpStudPortalJBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpStudPortalJBtnMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/profile.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/video.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setToolTipText("Fire hazards informative videos");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(moodSwingJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateVitalRecJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(notificationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HelpStudPortalJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewSanctionsJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(updateVitalRecJBtn)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(viewSanctionsJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(HelpStudPortalJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(checkAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(moodSwingJBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))))
                    .addComponent(notificationScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(171, 171, 171))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateVitalRecJBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateVitalRecJBtnFocusGained
        // TODO add your handling code here:
        updateVitalRecJBtn.setBackground(Color.YELLOW);
    }//GEN-LAST:event_updateVitalRecJBtnFocusGained

    private void updateVitalRecJBtnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateVitalRecJBtnFocusLost
        // TODO add your handling code here:
        updateVitalRecJBtn.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_updateVitalRecJBtnFocusLost

    private void updateVitalRecJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateVitalRecJBtnActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        HealthRecordWorkAreaJPanel healthRecordWorkAreaJPanel = new HealthRecordWorkAreaJPanel(userProcessContainer, acc, enterprise, ecosystem, false);
        userProcessContainer.add("healthRecordWorkAreaJPanel", healthRecordWorkAreaJPanel);
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_updateVitalRecJBtnActionPerformed

    private void moodSwingJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodSwingJBtnActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        MoodSwingsWorkAreaJPanel moodSwingsWorkAreaJPanel = new MoodSwingsWorkAreaJPanel(userProcessContainer, acc, enterprise, ecosystem);
        userProcessContainer.add("moodSwingsWorkAreaJPanel", moodSwingsWorkAreaJPanel);
        crdLyt.next(userProcessContainer);
    }//GEN-LAST:event_moodSwingJBtnActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (jList1.getSelectedValue() != null) {
            //  System.out.println("value................"+jList1.getSelectedValue());
            String[] parts = String.valueOf(jList1.getSelectedValue()).split("\\(");
            String[] dateRetrive = parts[1].split("\\)");
            int idMatch = Integer.valueOf(parts[0]);

            for (WorkRequest request : acc.getWorkQueue().getWorkRequestList()) {
                DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
                String reportDate = df.format(request.getRequestDate());
                //    System.out.println("request.getId()................"+request.getId());
                if ((Integer.valueOf(request.getId()) == idMatch) && (reportDate.equals(dateRetrive[0]))) {
                    request.setCheckedNotification(true);
                    if (request instanceof PersonalHealthIssueWorkRequest) {
                        HealthIssueRequestJPanel healthIssueRequestJPanel = new HealthIssueRequestJPanel(userProcessContainer, acc, enterprise, ecosystem);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        userProcessContainer.add("healthIssueRequestJPanel", healthIssueRequestJPanel);
                        layout.next(userProcessContainer);

                    } else if (request instanceof StudentPortalWorkRequest && ((StudentPortalWorkRequest) request).getCourseId().isEmpty()) {
                        StudentPortalJPanel studentPortalJPanel = new StudentPortalJPanel(userProcessContainer, acc, enterprise, ecosystem);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        userProcessContainer.add("studentPortalJPanel", studentPortalJPanel);
                        layout.next(userProcessContainer);
                    } else if (request instanceof StudentPortalWorkRequest && (!((StudentPortalWorkRequest) request).getCourseId().isEmpty())) {
                        StudentTeacherMentorPortalJPanel studentTeacherMentorPortalJPanel = new StudentTeacherMentorPortalJPanel(userProcessContainer, acc, enterprise, ecosystem);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        userProcessContainer.add("studentTeacherMentorPortalJPanel", studentTeacherMentorPortalJPanel);
                        layout.next(userProcessContainer);
                    } else if (request instanceof FinancialWorkRequest) {
                        StudentTeacherMentorPortalJPanel studentTeacherMentorPortalJPanel = new StudentTeacherMentorPortalJPanel(userProcessContainer, acc, enterprise, ecosystem);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        userProcessContainer.add("studentTeacherMentorPortalJPanel", studentTeacherMentorPortalJPanel);
                        layout.next(userProcessContainer);
                    }
                    break;
                } 
            }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void checkAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkAppointmentsMouseClicked
        // TODO add your handling code here:
        StudentTeacherMentorPortalJPanel studentTeacherMentorPortalJPanel = new StudentTeacherMentorPortalJPanel(userProcessContainer, acc, enterprise, ecosystem);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("studentTeacherMentorPortalJPanel", studentTeacherMentorPortalJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_checkAppointmentsMouseClicked

    private void HelpStudPortalJBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpStudPortalJBtnMouseClicked
        // TODO add your handling code here:
        StudentPortalJPanel studentPortalJPanel = new StudentPortalJPanel(userProcessContainer, acc, enterprise, ecosystem);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("studentPortalJPanel", studentPortalJPanel);
        layout.next(userProcessContainer);

    }//GEN-LAST:event_HelpStudPortalJBtnMouseClicked

    private void viewSanctionsJBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewSanctionsJBtnMouseClicked
        // TODO add your handling code here:

        StudentSanctionFinanceJPanel studentSanctionFinanceJPanel = new StudentSanctionFinanceJPanel(userProcessContainer, acc, enterprise, ecosystem);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("studentSanctionFinanceJPanel", studentSanctionFinanceJPanel);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewSanctionsJBtnMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof StudentOrganization) {
                for (UserAccount userAcc : org.getUserAccountDirectory().getUserAccountList()) {
                    if (userAcc == acc) {
                        AddPersonJPanel reviewPersonProfile = new AddPersonJPanel(userProcessContainer, org.getPersonDirectory(), ecosystem, enterprise, userAcc);
                        userProcessContainer.add("reviewPersonProfile", reviewPersonProfile);
                        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                        layout.next(userProcessContainer);
                    }
                }
            }
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        showVideo("http://youtu.be/rpf2xeCgX1Q");
    }//GEN-LAST:event_jLabel3MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HelpStudPortalJBtn;
    private javax.swing.JLabel checkAppointments;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton moodSwingJBtn;
    private javax.swing.JPanel notificationJPanel;
    private javax.swing.JScrollPane notificationScrollPane;
    private javax.swing.JButton updateVitalRecJBtn;
    private javax.swing.JLabel viewSanctionsJBtn;
    // End of variables declaration//GEN-END:variables
}
